// Shared types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metacensus/v1/common.proto

package metacensusv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Closed vocabulary: an unrecognized value fails to decode rather than
// reaching a verifier. See README.md, "The signing chain", before adding one.
type UserSignature_Alg int32

const (
	UserSignature_Unspecified UserSignature_Alg = 0
	// JOSE fixed-width r||s, never DER.
	UserSignature_Es384 UserSignature_Alg = 1
)

// Enum value maps for UserSignature_Alg.
var (
	UserSignature_Alg_name = map[int32]string{
		0: "Unspecified",
		1: "Es384",
	}
	UserSignature_Alg_value = map[string]int32{
		"Unspecified": 0,
		"Es384":       1,
	}
)

func (x UserSignature_Alg) Enum() *UserSignature_Alg {
	p := new(UserSignature_Alg)
	*p = x
	return p
}

func (x UserSignature_Alg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSignature_Alg) Descriptor() protoreflect.EnumDescriptor {
	return file_metacensus_v1_common_proto_enumTypes[0].Descriptor()
}

func (UserSignature_Alg) Type() protoreflect.EnumType {
	return &file_metacensus_v1_common_proto_enumTypes[0]
}

func (x UserSignature_Alg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSignature_Alg.Descriptor instead.
func (UserSignature_Alg) EnumDescriptor() ([]byte, []int) {
	return file_metacensus_v1_common_proto_rawDescGZIP(), []int{3, 0}
}

// Pagination envelope for list responses; no route paginates yet.
type ListMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based.
	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Across all pages, not just this one.
	Total         int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetadata) Reset() {
	*x = ListMetadata{}
	mi := &file_metacensus_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetadata) ProtoMessage() {}

func (x *ListMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetadata.ProtoReflect.Descriptor instead.
func (*ListMetadata) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ListMetadata) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMetadata) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMetadata) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_metacensus_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_common_proto_rawDescGZIP(), []int{1}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_metacensus_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *HealthcheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// One participant's signature over one content message. Not verified at the
// API edge — see README.md, "The signing chain".
type UserSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty only on the sign-up that enrolls the key; public_key carries it
	// inline there instead.
	SignerId string `protobuf:"bytes,1,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	// base64url SHA-256 of public_key's SPKI DER.
	KeyId string            `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Alg   UserSignature_Alg `protobuf:"varint,3,opt,name=alg,proto3,enum=metacensus.v1.UserSignature_Alg" json:"alg,omitempty"`
	// base64url SPKI DER; set only on the sign-up that enrolls the key.
	PublicKey string `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The signer's claimed time, not the server's — see `recorded` on signed
	// records for what the pair does and does not bound.
	SigningTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=signing_time,json=signingTime,proto3" json:"signing_time,omitempty"`
	// Exactly how this signature is computed and checked; changing the
	// canonicalization, digest, or encoding changes this string.
	Spec string `protobuf:"bytes,6,opt,name=spec,proto3" json:"spec,omitempty"`
	// Full proto name of the message `content` holds, e.g.
	// "metacensus.v1.PropContent". Stops a signature over one type being
	// replayed as another.
	ContentType string `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Excluded from its own digest by being emptied, not dropped.
	Value         string `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignature) Reset() {
	*x = UserSignature{}
	mi := &file_metacensus_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignature) ProtoMessage() {}

func (x *UserSignature) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignature.ProtoReflect.Descriptor instead.
func (*UserSignature) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *UserSignature) GetSignerId() string {
	if x != nil {
		return x.SignerId
	}
	return ""
}

func (x *UserSignature) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UserSignature) GetAlg() UserSignature_Alg {
	if x != nil {
		return x.Alg
	}
	return UserSignature_Unspecified
}

func (x *UserSignature) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UserSignature) GetSigningTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SigningTime
	}
	return nil
}

func (x *UserSignature) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *UserSignature) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UserSignature) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// The part of a user record its owner signs. Lives here, not user.proto,
// because auth.proto's SignUpRequest and user.proto's User both need it.
type UserContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContent) Reset() {
	*x = UserContent{}
	mi := &file_metacensus_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContent) ProtoMessage() {}

func (x *UserContent) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContent.ProtoReflect.Descriptor instead.
func (*UserContent) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *UserContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserContent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserContent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_metacensus_v1_common_proto protoreflect.FileDescriptor

const file_metacensus_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1ametacensus/v1/common.proto\x12\rmetacensus.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\fListMetadata\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\x14\n" +
	"\x12HealthcheckRequest\"-\n" +
	"\x13HealthcheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xc5\x02\n" +
	"\rUserSignature\x12\x1b\n" +
	"\tsigner_id\x18\x01 \x01(\tR\bsignerId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x122\n" +
	"\x03alg\x18\x03 \x01(\x0e2 .metacensus.v1.UserSignature.AlgR\x03alg\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12=\n" +
	"\fsigning_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vsigningTime\x12\x12\n" +
	"\x04spec\x18\x06 \x01(\tR\x04spec\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12\x14\n" +
	"\x05value\x18\b \x01(\tR\x05value\"!\n" +
	"\x03Alg\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\t\n" +
	"\x05Es384\x10\x01\"Q\n" +
	"\vUserContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry2z\n" +
	"\fHealthRoutes\x12j\n" +
	"\vHealthcheck\x12!.metacensus.v1.HealthcheckRequest\x1a\".metacensus.v1.HealthcheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/healthcheckB9Z7github.com/metacensus/api/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_common_proto_rawDescOnce sync.Once
	file_metacensus_v1_common_proto_rawDescData []byte
)

func file_metacensus_v1_common_proto_rawDescGZIP() []byte {
	file_metacensus_v1_common_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_common_proto_rawDesc), len(file_metacensus_v1_common_proto_rawDesc)))
	})
	return file_metacensus_v1_common_proto_rawDescData
}

var file_metacensus_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metacensus_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metacensus_v1_common_proto_goTypes = []any{
	(UserSignature_Alg)(0),        // 0: metacensus.v1.UserSignature.Alg
	(*ListMetadata)(nil),          // 1: metacensus.v1.ListMetadata
	(*HealthcheckRequest)(nil),    // 2: metacensus.v1.HealthcheckRequest
	(*HealthcheckResponse)(nil),   // 3: metacensus.v1.HealthcheckResponse
	(*UserSignature)(nil),         // 4: metacensus.v1.UserSignature
	(*UserContent)(nil),           // 5: metacensus.v1.UserContent
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_metacensus_v1_common_proto_depIdxs = []int32{
	0, // 0: metacensus.v1.UserSignature.alg:type_name -> metacensus.v1.UserSignature.Alg
	6, // 1: metacensus.v1.UserSignature.signing_time:type_name -> google.protobuf.Timestamp
	2, // 2: metacensus.v1.HealthRoutes.Healthcheck:input_type -> metacensus.v1.HealthcheckRequest
	3, // 3: metacensus.v1.HealthRoutes.Healthcheck:output_type -> metacensus.v1.HealthcheckResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metacensus_v1_common_proto_init() }
func file_metacensus_v1_common_proto_init() {
	if File_metacensus_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_common_proto_rawDesc), len(file_metacensus_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metacensus_v1_common_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_common_proto_depIdxs,
		EnumInfos:         file_metacensus_v1_common_proto_enumTypes,
		MessageInfos:      file_metacensus_v1_common_proto_msgTypes,
	}.Build()
	File_metacensus_v1_common_proto = out.File
	file_metacensus_v1_common_proto_goTypes = nil
	file_metacensus_v1_common_proto_depIdxs = nil
}
