// Data extraction: one reviewer's pass over one paper against one protocol.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metacensus/v1/extraction.proto

package metacensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataExtractionReview is one reviewer's complete pass over a paper.
//
// It is the container: a review groups the individual `DataExtraction` values,
// one per protocol element. A topic requires `Topic.minimum_extraction_reviews`
// of these per paper before the paper counts as extracted, which is what the
// topic dashboard's "n / m" counter renders.
//
// demo only. infra routes `/topic/{topicId}/paper/{paperId}/protocol` for the
// same concept and leaves it `handleUnimplemented` (HTTP 501).
type DataExtractionReview struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaperId    string                 `protobuf:"bytes,2,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	ProtocolId string                 `protobuf:"bytes,3,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	TopicId    string                 `protobuf:"bytes,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	// SOURCE CONFLICT: demo's table has a `user_id` column but its create handler
	// never sets it, so every review is anonymous. Since the whole point of
	// requiring several reviews is that they come from different people, this is
	// a functional gap, not a cosmetic one — nothing today stops one user
	// satisfying the minimum alone.
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataExtractionReview) Reset() {
	*x = DataExtractionReview{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionReview) ProtoMessage() {}

func (x *DataExtractionReview) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionReview.ProtoReflect.Descriptor instead.
func (*DataExtractionReview) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{0}
}

func (x *DataExtractionReview) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataExtractionReview) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *DataExtractionReview) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *DataExtractionReview) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *DataExtractionReview) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataExtractionReview) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DataExtractionReview) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DataExtraction is one answered protocol element within a review.
type DataExtraction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaperId           string                 `protobuf:"bytes,2,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	ProtocolId        string                 `protobuf:"bytes,3,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	ProtocolElementId string                 `protobuf:"bytes,4,opt,name=protocol_element_id,json=protocolElementId,proto3" json:"protocol_element_id,omitempty"`
	// SOURCE CONFLICT: demo's table has this column and its extraction handlers
	// never set it, same as on the review.
	UserId                 string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DataExtractionReviewId string `protobuf:"bytes,6,opt,name=data_extraction_review_id,json=dataExtractionReviewId,proto3" json:"data_extraction_review_id,omitempty"`
	// The extracted value.
	//
	// SOURCE CONFLICT, and under-determined. `types/DataExtraction.ts` declares
	// `data: string`; demo's column is `jsonb` typed `any`. A string is right for
	// `text`, `number`, `date`, `textarea` and `radio` elements, which is what
	// the SPA's form produces today. It is not obviously right for `checkbox`
	// elements, where several options can be selected — the SPA's checkbox
	// handling would have to be read closely, or the shape decided deliberately,
	// before this can be called settled. Declared as a string because that is
	// what the client declares; flagged because `jsonb` was chosen for a reason.
	Data string `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	// Where in the PDF the value was read from, so a later reviewer can jump to
	// it. Absent when the reviewer typed the value instead of selecting it.
	SourceLocation []*SourceLocationPage  `protobuf:"bytes,8,rep,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataExtraction) Reset() {
	*x = DataExtraction{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtraction) ProtoMessage() {}

func (x *DataExtraction) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtraction.ProtoReflect.Descriptor instead.
func (*DataExtraction) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{1}
}

func (x *DataExtraction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataExtraction) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *DataExtraction) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *DataExtraction) GetProtocolElementId() string {
	if x != nil {
		return x.ProtocolElementId
	}
	return ""
}

func (x *DataExtraction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataExtraction) GetDataExtractionReviewId() string {
	if x != nil {
		return x.DataExtractionReviewId
	}
	return ""
}

func (x *DataExtraction) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DataExtraction) GetSourceLocation() []*SourceLocationPage {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *DataExtraction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DataExtraction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SourceLocationPage is the highlighted rectangles on one page of the PDF.
type SourceLocationPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Rects         []*SourceRect          `protobuf:"bytes,2,rep,name=rects,proto3" json:"rects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocationPage) Reset() {
	*x = SourceLocationPage{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocationPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocationPage) ProtoMessage() {}

func (x *SourceLocationPage) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocationPage.ProtoReflect.Descriptor instead.
func (*SourceLocationPage) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{2}
}

func (x *SourceLocationPage) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SourceLocationPage) GetRects() []*SourceRect {
	if x != nil {
		return x.Rects
	}
	return nil
}

// SourceRect is one highlight rectangle, in the PDF viewer's coordinate space.
//
// `w`/`h` rather than `width`/`height`: `types/DataExtraction.ts` and demo's
// column type both use the short names.
type SourceRect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	W             float64                `protobuf:"fixed64,3,opt,name=w,proto3" json:"w,omitempty"`
	H             float64                `protobuf:"fixed64,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceRect) Reset() {
	*x = SourceRect{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRect) ProtoMessage() {}

func (x *SourceRect) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRect.ProtoReflect.Descriptor instead.
func (*SourceRect) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{3}
}

func (x *SourceRect) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SourceRect) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SourceRect) GetW() float64 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *SourceRect) GetH() float64 {
	if x != nil {
		return x.H
	}
	return 0
}

// DataExtractionInput is one element's value as submitted.
//
// Distinct from `DataExtraction` because a submission has no id, no review id
// and no timestamps — the server assigns those.
type DataExtractionInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolElementId string                 `protobuf:"bytes,1,opt,name=protocol_element_id,json=protocolElementId,proto3" json:"protocol_element_id,omitempty"`
	ProtocolId        string                 `protobuf:"bytes,2,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	PaperId           string                 `protobuf:"bytes,3,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	Data              string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	SourceLocation    []*SourceLocationPage  `protobuf:"bytes,5,rep,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DataExtractionInput) Reset() {
	*x = DataExtractionInput{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionInput) ProtoMessage() {}

func (x *DataExtractionInput) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionInput.ProtoReflect.Descriptor instead.
func (*DataExtractionInput) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{4}
}

func (x *DataExtractionInput) GetProtocolElementId() string {
	if x != nil {
		return x.ProtocolElementId
	}
	return ""
}

func (x *DataExtractionInput) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *DataExtractionInput) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *DataExtractionInput) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DataExtractionInput) GetSourceLocation() []*SourceLocationPage {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

// DataExtractionListRequest is the body of `POST /extraction`.
//
// SOURCE CONFLICT: another read over POST. And a quirk demo's own comment calls
// out — when either field is missing it returns *HTTP 200* with
// `{"error": "Missing required fields"}` in the body, so a client checking
// `response.ok` sails past the failure. That is a 400.
type DataExtractionListRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PaperId            string                 `protobuf:"bytes,1,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	ExtractionReviewId string                 `protobuf:"bytes,2,opt,name=extraction_review_id,json=extractionReviewId,proto3" json:"extraction_review_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DataExtractionListRequest) Reset() {
	*x = DataExtractionListRequest{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionListRequest) ProtoMessage() {}

func (x *DataExtractionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionListRequest.ProtoReflect.Descriptor instead.
func (*DataExtractionListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{5}
}

func (x *DataExtractionListRequest) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *DataExtractionListRequest) GetExtractionReviewId() string {
	if x != nil {
		return x.ExtractionReviewId
	}
	return ""
}

// DataExtractionList is the response to `POST /extraction`.
//
// SOURCE CONFLICT: demo returns a bare JSON array.
type DataExtractionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataExtraction      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataExtractionList) Reset() {
	*x = DataExtractionList{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionList) ProtoMessage() {}

func (x *DataExtractionList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionList.ProtoReflect.Descriptor instead.
func (*DataExtractionList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{6}
}

func (x *DataExtractionList) GetItems() []*DataExtraction {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DataExtractionList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DataExtractionReviewListRequest is the body of `POST /extraction-review`.
//
// All three of `topic_id`, `paper_id` and `protocol_id` are required; demo
// rejects a request missing any of them. It also `decodeURIComponent()`s
// `topic_id` — see `PaperListRequest`.
type DataExtractionReviewListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PaperId       string                 `protobuf:"bytes,2,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	ProtocolId    string                 `protobuf:"bytes,3,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataExtractionReviewListRequest) Reset() {
	*x = DataExtractionReviewListRequest{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionReviewListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionReviewListRequest) ProtoMessage() {}

func (x *DataExtractionReviewListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionReviewListRequest.ProtoReflect.Descriptor instead.
func (*DataExtractionReviewListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{7}
}

func (x *DataExtractionReviewListRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *DataExtractionReviewListRequest) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *DataExtractionReviewListRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *DataExtractionReviewListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DataExtractionReviewListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// DataExtractionReviewList is the response to `POST /extraction-review`.
//
// SOURCE CONFLICT: demo returns a bare JSON array. The SPA reads only its
// `.length`, to render the "reviews so far" counter.
type DataExtractionReviewList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*DataExtractionReview `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataExtractionReviewList) Reset() {
	*x = DataExtractionReviewList{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionReviewList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionReviewList) ProtoMessage() {}

func (x *DataExtractionReviewList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionReviewList.ProtoReflect.Descriptor instead.
func (*DataExtractionReviewList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{8}
}

func (x *DataExtractionReviewList) GetItems() []*DataExtractionReview {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DataExtractionReviewList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DataExtractionCreateRequest is the body of `POST /extraction/create`.
//
// Creates the review and all of its extractions in one call.
type DataExtractionCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PaperId       string                 `protobuf:"bytes,2,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	ProtocolId    string                 `protobuf:"bytes,3,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	Data          []*DataExtractionInput `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataExtractionCreateRequest) Reset() {
	*x = DataExtractionCreateRequest{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionCreateRequest) ProtoMessage() {}

func (x *DataExtractionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionCreateRequest.ProtoReflect.Descriptor instead.
func (*DataExtractionCreateRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{9}
}

func (x *DataExtractionCreateRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *DataExtractionCreateRequest) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *DataExtractionCreateRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *DataExtractionCreateRequest) GetData() []*DataExtractionInput {
	if x != nil {
		return x.Data
	}
	return nil
}

// DataExtractionEditRequest is the body of `POST /extraction/edit`.
//
// Same as create but against an existing review. demo upserts element by
// element: it looks each one up by
// `(protocolElementId, protocolId, paperId, reviewId)` and inserts when there is
// no match, so an edit can add answers the original submission omitted.
type DataExtractionEditRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TopicId            string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PaperId            string                 `protobuf:"bytes,2,opt,name=paper_id,json=paperId,proto3" json:"paper_id,omitempty"`
	ProtocolId         string                 `protobuf:"bytes,3,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	ExtractionReviewId string                 `protobuf:"bytes,4,opt,name=extraction_review_id,json=extractionReviewId,proto3" json:"extraction_review_id,omitempty"`
	Data               []*DataExtractionInput `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DataExtractionEditRequest) Reset() {
	*x = DataExtractionEditRequest{}
	mi := &file_metacensus_v1_extraction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExtractionEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExtractionEditRequest) ProtoMessage() {}

func (x *DataExtractionEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_extraction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExtractionEditRequest.ProtoReflect.Descriptor instead.
func (*DataExtractionEditRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_extraction_proto_rawDescGZIP(), []int{10}
}

func (x *DataExtractionEditRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *DataExtractionEditRequest) GetPaperId() string {
	if x != nil {
		return x.PaperId
	}
	return ""
}

func (x *DataExtractionEditRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *DataExtractionEditRequest) GetExtractionReviewId() string {
	if x != nil {
		return x.ExtractionReviewId
	}
	return ""
}

func (x *DataExtractionEditRequest) GetData() []*DataExtractionInput {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_metacensus_v1_extraction_proto protoreflect.FileDescriptor

const file_metacensus_v1_extraction_proto_rawDesc = "" +
	"\n" +
	"\x1emetacensus/v1/extraction.proto\x12\rmetacensus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametacensus/v1/common.proto\"\x8c\x02\n" +
	"\x14DataExtractionReview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bpaper_id\x18\x02 \x01(\tR\apaperId\x12\x1f\n" +
	"\vprotocol_id\x18\x03 \x01(\tR\n" +
	"protocolId\x12\x19\n" +
	"\btopic_id\x18\x04 \x01(\tR\atopicId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb6\x03\n" +
	"\x0eDataExtraction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bpaper_id\x18\x02 \x01(\tR\apaperId\x12\x1f\n" +
	"\vprotocol_id\x18\x03 \x01(\tR\n" +
	"protocolId\x12.\n" +
	"\x13protocol_element_id\x18\x04 \x01(\tR\x11protocolElementId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x129\n" +
	"\x19data_extraction_review_id\x18\x06 \x01(\tR\x16dataExtractionReviewId\x12\x12\n" +
	"\x04data\x18\a \x01(\tR\x04data\x12J\n" +
	"\x0fsource_location\x18\b \x03(\v2!.metacensus.v1.SourceLocationPageR\x0esourceLocation\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Y\n" +
	"\x12SourceLocationPage\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12/\n" +
	"\x05rects\x18\x02 \x03(\v2\x19.metacensus.v1.SourceRectR\x05rects\"D\n" +
	"\n" +
	"SourceRect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x01R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x01R\x01h\"\xe1\x01\n" +
	"\x13DataExtractionInput\x12.\n" +
	"\x13protocol_element_id\x18\x01 \x01(\tR\x11protocolElementId\x12\x1f\n" +
	"\vprotocol_id\x18\x02 \x01(\tR\n" +
	"protocolId\x12\x19\n" +
	"\bpaper_id\x18\x03 \x01(\tR\apaperId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12J\n" +
	"\x0fsource_location\x18\x05 \x03(\v2!.metacensus.v1.SourceLocationPageR\x0esourceLocation\"h\n" +
	"\x19DataExtractionListRequest\x12\x19\n" +
	"\bpaper_id\x18\x01 \x01(\tR\apaperId\x120\n" +
	"\x14extraction_review_id\x18\x02 \x01(\tR\x12extractionReviewId\"\x82\x01\n" +
	"\x12DataExtractionList\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.metacensus.v1.DataExtractionR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\"\xa2\x01\n" +
	"\x1fDataExtractionReviewListRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x19\n" +
	"\bpaper_id\x18\x02 \x01(\tR\apaperId\x12\x1f\n" +
	"\vprotocol_id\x18\x03 \x01(\tR\n" +
	"protocolId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x8e\x01\n" +
	"\x18DataExtractionReviewList\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.metacensus.v1.DataExtractionReviewR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\"\xac\x01\n" +
	"\x1bDataExtractionCreateRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x19\n" +
	"\bpaper_id\x18\x02 \x01(\tR\apaperId\x12\x1f\n" +
	"\vprotocol_id\x18\x03 \x01(\tR\n" +
	"protocolId\x126\n" +
	"\x04data\x18\x04 \x03(\v2\".metacensus.v1.DataExtractionInputR\x04data\"\xdc\x01\n" +
	"\x19DataExtractionEditRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x19\n" +
	"\bpaper_id\x18\x02 \x01(\tR\apaperId\x12\x1f\n" +
	"\vprotocol_id\x18\x03 \x01(\tR\n" +
	"protocolId\x120\n" +
	"\x14extraction_review_id\x18\x04 \x01(\tR\x12extractionReviewId\x126\n" +
	"\x04data\x18\x05 \x03(\v2\".metacensus.v1.DataExtractionInputR\x04dataBAZ?github.com/metacensus/ui/contract/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_extraction_proto_rawDescOnce sync.Once
	file_metacensus_v1_extraction_proto_rawDescData []byte
)

func file_metacensus_v1_extraction_proto_rawDescGZIP() []byte {
	file_metacensus_v1_extraction_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_extraction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_extraction_proto_rawDesc), len(file_metacensus_v1_extraction_proto_rawDesc)))
	})
	return file_metacensus_v1_extraction_proto_rawDescData
}

var file_metacensus_v1_extraction_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_metacensus_v1_extraction_proto_goTypes = []any{
	(*DataExtractionReview)(nil),            // 0: metacensus.v1.DataExtractionReview
	(*DataExtraction)(nil),                  // 1: metacensus.v1.DataExtraction
	(*SourceLocationPage)(nil),              // 2: metacensus.v1.SourceLocationPage
	(*SourceRect)(nil),                      // 3: metacensus.v1.SourceRect
	(*DataExtractionInput)(nil),             // 4: metacensus.v1.DataExtractionInput
	(*DataExtractionListRequest)(nil),       // 5: metacensus.v1.DataExtractionListRequest
	(*DataExtractionList)(nil),              // 6: metacensus.v1.DataExtractionList
	(*DataExtractionReviewListRequest)(nil), // 7: metacensus.v1.DataExtractionReviewListRequest
	(*DataExtractionReviewList)(nil),        // 8: metacensus.v1.DataExtractionReviewList
	(*DataExtractionCreateRequest)(nil),     // 9: metacensus.v1.DataExtractionCreateRequest
	(*DataExtractionEditRequest)(nil),       // 10: metacensus.v1.DataExtractionEditRequest
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
	(*ListMetadata)(nil),                    // 12: metacensus.v1.ListMetadata
}
var file_metacensus_v1_extraction_proto_depIdxs = []int32{
	11, // 0: metacensus.v1.DataExtractionReview.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: metacensus.v1.DataExtractionReview.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: metacensus.v1.DataExtraction.source_location:type_name -> metacensus.v1.SourceLocationPage
	11, // 3: metacensus.v1.DataExtraction.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: metacensus.v1.DataExtraction.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: metacensus.v1.SourceLocationPage.rects:type_name -> metacensus.v1.SourceRect
	2,  // 6: metacensus.v1.DataExtractionInput.source_location:type_name -> metacensus.v1.SourceLocationPage
	1,  // 7: metacensus.v1.DataExtractionList.items:type_name -> metacensus.v1.DataExtraction
	12, // 8: metacensus.v1.DataExtractionList.metadata:type_name -> metacensus.v1.ListMetadata
	0,  // 9: metacensus.v1.DataExtractionReviewList.items:type_name -> metacensus.v1.DataExtractionReview
	12, // 10: metacensus.v1.DataExtractionReviewList.metadata:type_name -> metacensus.v1.ListMetadata
	4,  // 11: metacensus.v1.DataExtractionCreateRequest.data:type_name -> metacensus.v1.DataExtractionInput
	4,  // 12: metacensus.v1.DataExtractionEditRequest.data:type_name -> metacensus.v1.DataExtractionInput
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_metacensus_v1_extraction_proto_init() }
func file_metacensus_v1_extraction_proto_init() {
	if File_metacensus_v1_extraction_proto != nil {
		return
	}
	file_metacensus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_extraction_proto_rawDesc), len(file_metacensus_v1_extraction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacensus_v1_extraction_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_extraction_proto_depIdxs,
		MessageInfos:      file_metacensus_v1_extraction_proto_msgTypes,
	}.Build()
	File_metacensus_v1_extraction_proto = out.File
	file_metacensus_v1_extraction_proto_goTypes = nil
	file_metacensus_v1_extraction_proto_depIdxs = nil
}
