// Data extraction: the values pulled from one paper against one protocol.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: metacensus/v1/extraction.proto

package metacensusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtractionRoutes_GetExtraction_FullMethodName    = "/metacensus.v1.ExtractionRoutes/GetExtraction"
	ExtractionRoutes_UpsertExtraction_FullMethodName = "/metacensus.v1.ExtractionRoutes/UpsertExtraction"
)

// ExtractionRoutesClient is the client API for ExtractionRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Declared as a gRPC service and served over HTTP by grpc-gateway, which
// transcodes from the google.api.http annotations below. No gRPC server runs.
type ExtractionRoutesClient interface {
	GetExtraction(ctx context.Context, in *DataExtractionGetRequest, opts ...grpc.CallOption) (*DataExtraction, error)
	UpsertExtraction(ctx context.Context, in *DataExtraction, opts ...grpc.CallOption) (*DataExtraction, error)
}

type extractionRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractionRoutesClient(cc grpc.ClientConnInterface) ExtractionRoutesClient {
	return &extractionRoutesClient{cc}
}

func (c *extractionRoutesClient) GetExtraction(ctx context.Context, in *DataExtractionGetRequest, opts ...grpc.CallOption) (*DataExtraction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataExtraction)
	err := c.cc.Invoke(ctx, ExtractionRoutes_GetExtraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractionRoutesClient) UpsertExtraction(ctx context.Context, in *DataExtraction, opts ...grpc.CallOption) (*DataExtraction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataExtraction)
	err := c.cc.Invoke(ctx, ExtractionRoutes_UpsertExtraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractionRoutesServer is the server API for ExtractionRoutes service.
// All implementations should embed UnimplementedExtractionRoutesServer
// for forward compatibility.
//
// Declared as a gRPC service and served over HTTP by grpc-gateway, which
// transcodes from the google.api.http annotations below. No gRPC server runs.
type ExtractionRoutesServer interface {
	GetExtraction(context.Context, *DataExtractionGetRequest) (*DataExtraction, error)
	UpsertExtraction(context.Context, *DataExtraction) (*DataExtraction, error)
}

// UnimplementedExtractionRoutesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtractionRoutesServer struct{}

func (UnimplementedExtractionRoutesServer) GetExtraction(context.Context, *DataExtractionGetRequest) (*DataExtraction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtraction not implemented")
}
func (UnimplementedExtractionRoutesServer) UpsertExtraction(context.Context, *DataExtraction) (*DataExtraction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertExtraction not implemented")
}
func (UnimplementedExtractionRoutesServer) testEmbeddedByValue() {}

// UnsafeExtractionRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractionRoutesServer will
// result in compilation errors.
type UnsafeExtractionRoutesServer interface {
	mustEmbedUnimplementedExtractionRoutesServer()
}

func RegisterExtractionRoutesServer(s grpc.ServiceRegistrar, srv ExtractionRoutesServer) {
	// If the following call pancis, it indicates UnimplementedExtractionRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtractionRoutes_ServiceDesc, srv)
}

func _ExtractionRoutes_GetExtraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataExtractionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionRoutesServer).GetExtraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionRoutes_GetExtraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionRoutesServer).GetExtraction(ctx, req.(*DataExtractionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtractionRoutes_UpsertExtraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataExtraction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractionRoutesServer).UpsertExtraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractionRoutes_UpsertExtraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractionRoutesServer).UpsertExtraction(ctx, req.(*DataExtraction))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtractionRoutes_ServiceDesc is the grpc.ServiceDesc for ExtractionRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtractionRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacensus.v1.ExtractionRoutes",
	HandlerType: (*ExtractionRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExtraction",
			Handler:    _ExtractionRoutes_GetExtraction_Handler,
		},
		{
			MethodName: "UpsertExtraction",
			Handler:    _ExtractionRoutes_UpsertExtraction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metacensus/v1/extraction.proto",
}
