// Literature search: the PubMed passthrough behind bulk paper import.
//
// EXCLUDED ENDPOINT: `POST /lit-search`.
//
// It takes `{db, querySearchTerm}`, runs NCBI E-utilities `esearch` followed by
// `esummary`, and returns the second response body verbatim. That body cannot be
// expressed as a protobuf message, and not for want of trying:
//
//   * `result` is a map keyed by PMID whose values are heterogeneous. Every key
//     maps to an article summary object except `uids`, which maps to an array of
//     strings. `map<string, PubMedSearchSummary>` cannot hold that, and
//     `google.protobuf.Struct` would describe it only by giving up on types
//     entirely.
//   * The article summary is NCBI's shape, not MetaCensus's. It has forty-odd
//     fields with names like `sorttitle`, `nlmuniqueid` and `doccontriblist`,
//     all lowercase-no-separator. protojson would render a proto field
//     `sort_title` as `sortTitle`, and the contract does not override field
//     naming — so every one of those fields would come out misspelled relative
//     to what NCBI sends and what `types/PubMed.ts` declares.
//   * It is not MetaCensus data. The response is whatever NCBI returns today; a
//     change at NCBI is not a change to this contract, and pinning their schema
//     into ours would make it look like one.
//
// The right fix is for the backend to project NCBI's summaries into a
// MetaCensus shape — the SPA reads about eight fields of the forty — at which
// point it becomes contractable. Until then, this endpoint stays out and
// `types/PubMed.ts` remains the client's own business.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metacensus/v1/lit_search.proto

package metacensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LitSearchAbstractRequest is the path and query parameters of
// `GET /lit-search/{id}/abstract?db=`.
//
// `id` is a PubMed uid. `db` is the NCBI database name; the SPA always sends
// `pubmed` and demo defaults to it.
type LitSearchAbstractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Db            string                 `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LitSearchAbstractRequest) Reset() {
	*x = LitSearchAbstractRequest{}
	mi := &file_metacensus_v1_lit_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LitSearchAbstractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LitSearchAbstractRequest) ProtoMessage() {}

func (x *LitSearchAbstractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_lit_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LitSearchAbstractRequest.ProtoReflect.Descriptor instead.
func (*LitSearchAbstractRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_lit_search_proto_rawDescGZIP(), []int{0}
}

func (x *LitSearchAbstractRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LitSearchAbstractRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

// LitSearchAbstract is the response to `GET /lit-search/{id}/abstract`: the
// abstract of one article, one entry per `<AbstractText>` element.
//
// Unlike `POST /lit-search` this one *is* contractable, because demo already
// projects NCBI's XML down to a list of strings rather than passing a foreign
// document through.
//
// SOURCE CONFLICT: demo returns a bare JSON array, which every response here
// must not be, so the contract wraps it. It is wrapped as a single resource
// with a named field rather than as a list with `items`, because these are the
// paragraphs of one abstract and not a collection of anything.
//
// SOURCE CONFLICT: demo maps over DOM nodes with `abstract.textContent`, which
// is nullable, so the array it returns is typed `(string | null)[]` and can
// contain nulls for empty elements. A repeated string field cannot hold a null;
// a backend implementing this contract should drop empty paragraphs instead.
type LitSearchAbstract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paragraphs    []string               `protobuf:"bytes,1,rep,name=paragraphs,proto3" json:"paragraphs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LitSearchAbstract) Reset() {
	*x = LitSearchAbstract{}
	mi := &file_metacensus_v1_lit_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LitSearchAbstract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LitSearchAbstract) ProtoMessage() {}

func (x *LitSearchAbstract) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_lit_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LitSearchAbstract.ProtoReflect.Descriptor instead.
func (*LitSearchAbstract) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_lit_search_proto_rawDescGZIP(), []int{1}
}

func (x *LitSearchAbstract) GetParagraphs() []string {
	if x != nil {
		return x.Paragraphs
	}
	return nil
}

var File_metacensus_v1_lit_search_proto protoreflect.FileDescriptor

const file_metacensus_v1_lit_search_proto_rawDesc = "" +
	"\n" +
	"\x1emetacensus/v1/lit_search.proto\x12\rmetacensus.v1\":\n" +
	"\x18LitSearchAbstractRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02db\x18\x02 \x01(\tR\x02db\"3\n" +
	"\x11LitSearchAbstract\x12\x1e\n" +
	"\n" +
	"paragraphs\x18\x01 \x03(\tR\n" +
	"paragraphsBAZ?github.com/metacensus/ui/contract/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_lit_search_proto_rawDescOnce sync.Once
	file_metacensus_v1_lit_search_proto_rawDescData []byte
)

func file_metacensus_v1_lit_search_proto_rawDescGZIP() []byte {
	file_metacensus_v1_lit_search_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_lit_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_lit_search_proto_rawDesc), len(file_metacensus_v1_lit_search_proto_rawDesc)))
	})
	return file_metacensus_v1_lit_search_proto_rawDescData
}

var file_metacensus_v1_lit_search_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metacensus_v1_lit_search_proto_goTypes = []any{
	(*LitSearchAbstractRequest)(nil), // 0: metacensus.v1.LitSearchAbstractRequest
	(*LitSearchAbstract)(nil),        // 1: metacensus.v1.LitSearchAbstract
}
var file_metacensus_v1_lit_search_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metacensus_v1_lit_search_proto_init() }
func file_metacensus_v1_lit_search_proto_init() {
	if File_metacensus_v1_lit_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_lit_search_proto_rawDesc), len(file_metacensus_v1_lit_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacensus_v1_lit_search_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_lit_search_proto_depIdxs,
		MessageInfos:      file_metacensus_v1_lit_search_proto_msgTypes,
	}.Build()
	File_metacensus_v1_lit_search_proto = out.File
	file_metacensus_v1_lit_search_proto_goTypes = nil
	file_metacensus_v1_lit_search_proto_depIdxs = nil
}
