// Propositions and votes: the consensus mechanism.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metacensus/v1/prop.proto

package metacensusv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type is what the proposition would do if it passed.
type PropContent_Type int32

const (
	PropContent_Unspecified              PropContent_Type = 0
	PropContent_Statement                PropContent_Type = 1
	PropContent_TopicQuestion            PropContent_Type = 2
	PropContent_TopicChange              PropContent_Type = 3
	PropContent_UserAdmit                PropContent_Type = 4
	PropContent_UserExpulse              PropContent_Type = 5
	PropContent_PaperExtractionComplete  PropContent_Type = 6
	PropContent_PaperIncludeMetaAnalysis PropContent_Type = 7
)

// Enum value maps for PropContent_Type.
var (
	PropContent_Type_name = map[int32]string{
		0: "Unspecified",
		1: "Statement",
		2: "TopicQuestion",
		3: "TopicChange",
		4: "UserAdmit",
		5: "UserExpulse",
		6: "PaperExtractionComplete",
		7: "PaperIncludeMetaAnalysis",
	}
	PropContent_Type_value = map[string]int32{
		"Unspecified":              0,
		"Statement":                1,
		"TopicQuestion":            2,
		"TopicChange":              3,
		"UserAdmit":                4,
		"UserExpulse":              5,
		"PaperExtractionComplete":  6,
		"PaperIncludeMetaAnalysis": 7,
	}
)

func (x PropContent_Type) Enum() *PropContent_Type {
	p := new(PropContent_Type)
	*p = x
	return p
}

func (x PropContent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropContent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_metacensus_v1_prop_proto_enumTypes[0].Descriptor()
}

func (PropContent_Type) Type() protoreflect.EnumType {
	return &file_metacensus_v1_prop_proto_enumTypes[0]
}

func (x PropContent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropContent_Type.Descriptor instead.
func (PropContent_Type) EnumDescriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{1, 0}
}

type VoteContent_Position int32

const (
	VoteContent_Unspecified VoteContent_Position = 0
	VoteContent_For         VoteContent_Position = 1
	VoteContent_Against     VoteContent_Position = 2
	VoteContent_Abstain     VoteContent_Position = 3
)

// Enum value maps for VoteContent_Position.
var (
	VoteContent_Position_name = map[int32]string{
		0: "Unspecified",
		1: "For",
		2: "Against",
		3: "Abstain",
	}
	VoteContent_Position_value = map[string]int32{
		"Unspecified": 0,
		"For":         1,
		"Against":     2,
		"Abstain":     3,
	}
)

func (x VoteContent_Position) Enum() *VoteContent_Position {
	p := new(VoteContent_Position)
	*p = x
	return p
}

func (x VoteContent_Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteContent_Position) Descriptor() protoreflect.EnumDescriptor {
	return file_metacensus_v1_prop_proto_enumTypes[1].Descriptor()
}

func (VoteContent_Position) Type() protoreflect.EnumType {
	return &file_metacensus_v1_prop_proto_enumTypes[1]
}

func (x VoteContent_Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteContent_Position.Descriptor instead.
func (VoteContent_Position) EnumDescriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{3, 0}
}

// Prop is a motion a topic's members vote on, as a signed record: the server's
// own fields, the content its author signed, and the signature over it.
//
// `author_id` and `created` used to sit here. They are gone, and nothing
// replaced them, because they were the unattested versions of what the
// signature now carries: the author is `user_signature.signer_id` and the
// authoring time is `user_signature.signing_time`, both inside the digest.
type Prop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minted by the server, outside the signature: the prop's address.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When the server recorded the write. The server's observation.
	Recorded      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=recorded,proto3" json:"recorded,omitempty"`
	Content       *PropContent           `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserSignature *UserSignature         `protobuf:"bytes,4,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prop) Reset() {
	*x = Prop{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prop) ProtoMessage() {}

func (x *Prop) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prop.ProtoReflect.Descriptor instead.
func (*Prop) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{0}
}

func (x *Prop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Prop) GetRecorded() *timestamppb.Timestamp {
	if x != nil {
		return x.Recorded
	}
	return nil
}

func (x *Prop) GetContent() *PropContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Prop) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

// PropContent is what a prop's author signs.
//
// It carries `topic_id` because a prop's topic is part of what the prop
// *means* — the same words put to a different topic are put to different voters
// — and the rule is that every id the path binds is inside the content and
// covered by the signature. It does not carry the prop's own id, which the
// server mints.
type PropContent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TopicId string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Type    PropContent_Type       `protobuf:"varint,2,opt,name=type,proto3,enum=metacensus.v1.PropContent_Type" json:"type,omitempty"`
	// The text of the proposition, and the text `VoteContent.citations` index
	// into.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropContent) Reset() {
	*x = PropContent{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropContent) ProtoMessage() {}

func (x *PropContent) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropContent.ProtoReflect.Descriptor instead.
func (*PropContent) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{1}
}

func (x *PropContent) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *PropContent) GetType() PropContent_Type {
	if x != nil {
		return x.Type
	}
	return PropContent_Unspecified
}

func (x *PropContent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Vote is one member's position on one prop, keyed by `(propId, userId)`: a
// second vote from the same user replaces the first rather than adding to it.
//
// It has no minted id — nothing about it is server-chosen but the recording
// time — because both halves of its key are in the content the voter signed.
type Vote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the server recorded the vote. Overwritten on every recast, and the
	// only ordering a reader may use: `user_signature.signing_time` is the
	// voter's own claim.
	Recorded      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	Content       *VoteContent           `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserSignature *UserSignature         `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{2}
}

func (x *Vote) GetRecorded() *timestamppb.Timestamp {
	if x != nil {
		return x.Recorded
	}
	return nil
}

func (x *Vote) GetContent() *VoteContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Vote) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

// VoteContent is what a voter signs.
//
// It carries every id that composes the vote's key, and every id the path
// binds: `prop_id` and `user_id` are the key, `topic_id` is the path's. That
// `user_id` is also `user_signature.signer_id` is deliberate redundancy rather
// than an oversight — the rule that content carries its own key is worth more
// than the observation that one particular id happens to be implied elsewhere.
// Both are inside one digest, so persistence rejects a record whose `user_id`
// and `signer_id` disagree: it is validly signed and self-inconsistent, which
// is the only way those two can differ.
type VoteContent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TopicId  string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PropId   string                 `protobuf:"bytes,2,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	UserId   string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Position VoteContent_Position   `protobuf:"varint,4,opt,name=position,proto3,enum=metacensus.v1.VoteContent_Position" json:"position,omitempty"`
	// Free-text rationale.
	Explanation string `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// Spans of the prop's `description` the voter highlighted. Meaningful only
	// for an `Against` vote; cleared when the position changes to any other.
	Citations     []*PropCitation `protobuf:"bytes,6,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteContent) Reset() {
	*x = VoteContent{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteContent) ProtoMessage() {}

func (x *VoteContent) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteContent.ProtoReflect.Descriptor instead.
func (*VoteContent) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{3}
}

func (x *VoteContent) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *VoteContent) GetPropId() string {
	if x != nil {
		return x.PropId
	}
	return ""
}

func (x *VoteContent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VoteContent) GetPosition() VoteContent_Position {
	if x != nil {
		return x.Position
	}
	return VoteContent_Unspecified
}

func (x *VoteContent) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *VoteContent) GetCitations() []*PropCitation {
	if x != nil {
		return x.Citations
	}
	return nil
}

// PropCitation is a half-open character range in a prop's `description`.
type PropCitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropCitation) Reset() {
	*x = PropCitation{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropCitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropCitation) ProtoMessage() {}

func (x *PropCitation) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropCitation.ProtoReflect.Descriptor instead.
func (*PropCitation) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{4}
}

func (x *PropCitation) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PropCitation) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type PropListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropListRequest) Reset() {
	*x = PropListRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropListRequest) ProtoMessage() {}

func (x *PropListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropListRequest.ProtoReflect.Descriptor instead.
func (*PropListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{5}
}

func (x *PropListRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

type PropList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Prop                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropList) Reset() {
	*x = PropList{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropList) ProtoMessage() {}

func (x *PropList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropList.ProtoReflect.Descriptor instead.
func (*PropList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{6}
}

func (x *PropList) GetItems() []*Prop {
	if x != nil {
		return x.Items
	}
	return nil
}

type PropGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PropId        string                 `protobuf:"bytes,2,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropGetRequest) Reset() {
	*x = PropGetRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropGetRequest) ProtoMessage() {}

func (x *PropGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropGetRequest.ProtoReflect.Descriptor instead.
func (*PropGetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{7}
}

func (x *PropGetRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *PropGetRequest) GetPropId() string {
	if x != nil {
		return x.PropId
	}
	return ""
}

// PropCreateRequest takes no author: it is `user_signature.signer_id`.
//
// `topic_id` appears twice on purpose — once at the top level, where the route
// binds it from the path, and once inside `content`, where it is signed. They
// must agree, and the generated binding refuses the request when they do not.
// That check is a good error message rather than a control: persistence keys
// the record off `content`, so a server that skipped the comparison would write
// the record the signature describes, not the one the URL asked for.
type PropCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Content       *PropContent           `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserSignature *UserSignature         `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropCreateRequest) Reset() {
	*x = PropCreateRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropCreateRequest) ProtoMessage() {}

func (x *PropCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropCreateRequest.ProtoReflect.Descriptor instead.
func (*PropCreateRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{8}
}

func (x *PropCreateRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *PropCreateRequest) GetContent() *PropContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PropCreateRequest) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

type VoteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PropId        string                 `protobuf:"bytes,2,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteListRequest) Reset() {
	*x = VoteListRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteListRequest) ProtoMessage() {}

func (x *VoteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteListRequest.ProtoReflect.Descriptor instead.
func (*VoteListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{9}
}

func (x *VoteListRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *VoteListRequest) GetPropId() string {
	if x != nil {
		return x.PropId
	}
	return ""
}

// VoteList is the only way to read a prop's votes.
type VoteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Vote                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteList) Reset() {
	*x = VoteList{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteList) ProtoMessage() {}

func (x *VoteList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteList.ProtoReflect.Descriptor instead.
func (*VoteList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{10}
}

func (x *VoteList) GetItems() []*Vote {
	if x != nil {
		return x.Items
	}
	return nil
}

// VoteSetRequest sets rather than creates: it replaces the caller's previous
// vote on this prop. Both path ids are repeated inside `content`, signed, and
// checked against the path; see PropCreateRequest.
type VoteSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PropId        string                 `protobuf:"bytes,2,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	Content       *VoteContent           `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserSignature *UserSignature         `protobuf:"bytes,4,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteSetRequest) Reset() {
	*x = VoteSetRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteSetRequest) ProtoMessage() {}

func (x *VoteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteSetRequest.ProtoReflect.Descriptor instead.
func (*VoteSetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{11}
}

func (x *VoteSetRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *VoteSetRequest) GetPropId() string {
	if x != nil {
		return x.PropId
	}
	return ""
}

func (x *VoteSetRequest) GetContent() *VoteContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VoteSetRequest) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

var File_metacensus_v1_prop_proto protoreflect.FileDescriptor

const file_metacensus_v1_prop_proto_rawDesc = "" +
	"\n" +
	"\x18metacensus/v1/prop.proto\x12\rmetacensus.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametacensus/v1/common.proto\"\xc9\x01\n" +
	"\x04Prop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\brecorded\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\brecorded\x124\n" +
	"\acontent\x18\x03 \x01(\v2\x1a.metacensus.v1.PropContentR\acontent\x12C\n" +
	"\x0euser_signature\x18\x04 \x01(\v2\x1c.metacensus.v1.UserSignatureR\ruserSignature\"\xa7\x02\n" +
	"\vPropContent\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.metacensus.v1.PropContent.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa5\x01\n" +
	"\x04Type\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\r\n" +
	"\tStatement\x10\x01\x12\x11\n" +
	"\rTopicQuestion\x10\x02\x12\x0f\n" +
	"\vTopicChange\x10\x03\x12\r\n" +
	"\tUserAdmit\x10\x04\x12\x0f\n" +
	"\vUserExpulse\x10\x05\x12\x1b\n" +
	"\x17PaperExtractionComplete\x10\x06\x12\x1c\n" +
	"\x18PaperIncludeMetaAnalysis\x10\a\"\xb9\x01\n" +
	"\x04Vote\x126\n" +
	"\brecorded\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\brecorded\x124\n" +
	"\acontent\x18\x02 \x01(\v2\x1a.metacensus.v1.VoteContentR\acontent\x12C\n" +
	"\x0euser_signature\x18\x03 \x01(\v2\x1c.metacensus.v1.UserSignatureR\ruserSignature\"\xb8\x02\n" +
	"\vVoteContent\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\aprop_id\x18\x02 \x01(\tR\x06propId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12?\n" +
	"\bposition\x18\x04 \x01(\x0e2#.metacensus.v1.VoteContent.PositionR\bposition\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x129\n" +
	"\tcitations\x18\x06 \x03(\v2\x1b.metacensus.v1.PropCitationR\tcitations\">\n" +
	"\bPosition\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\a\n" +
	"\x03For\x10\x01\x12\v\n" +
	"\aAgainst\x10\x02\x12\v\n" +
	"\aAbstain\x10\x03\"6\n" +
	"\fPropCitation\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\",\n" +
	"\x0fPropListRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"5\n" +
	"\bPropList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.metacensus.v1.PropR\x05items\"D\n" +
	"\x0ePropGetRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\aprop_id\x18\x02 \x01(\tR\x06propId\"\xa9\x01\n" +
	"\x11PropCreateRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x124\n" +
	"\acontent\x18\x02 \x01(\v2\x1a.metacensus.v1.PropContentR\acontent\x12C\n" +
	"\x0euser_signature\x18\x03 \x01(\v2\x1c.metacensus.v1.UserSignatureR\ruserSignature\"E\n" +
	"\x0fVoteListRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\aprop_id\x18\x02 \x01(\tR\x06propId\"5\n" +
	"\bVoteList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.metacensus.v1.VoteR\x05items\"\xbf\x01\n" +
	"\x0eVoteSetRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\aprop_id\x18\x02 \x01(\tR\x06propId\x124\n" +
	"\acontent\x18\x03 \x01(\v2\x1a.metacensus.v1.VoteContentR\acontent\x12C\n" +
	"\x0euser_signature\x18\x04 \x01(\v2\x1c.metacensus.v1.UserSignatureR\ruserSignature2\xa9\x04\n" +
	"\n" +
	"PropRoutes\x12d\n" +
	"\tListProps\x12\x1e.metacensus.v1.PropListRequest\x1a\x17.metacensus.v1.PropList\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/topic/{topic_id}/prop\x12g\n" +
	"\aGetProp\x12\x1d.metacensus.v1.PropGetRequest\x1a\x13.metacensus.v1.Prop\"(\x82\xd3\xe4\x93\x02\"\x12 /topic/{topic_id}/prop/{prop_id}\x12f\n" +
	"\n" +
	"CreateProp\x12 .metacensus.v1.PropCreateRequest\x1a\x13.metacensus.v1.Prop\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/topic/{topic_id}/prop\x12s\n" +
	"\tListVotes\x12\x1e.metacensus.v1.VoteListRequest\x1a\x17.metacensus.v1.VoteList\"-\x82\xd3\xe4\x93\x02'\x12%/topic/{topic_id}/prop/{prop_id}/vote\x12o\n" +
	"\aSetVote\x12\x1d.metacensus.v1.VoteSetRequest\x1a\x13.metacensus.v1.Vote\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/topic/{topic_id}/prop/{prop_id}/voteB9Z7github.com/metacensus/api/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_prop_proto_rawDescOnce sync.Once
	file_metacensus_v1_prop_proto_rawDescData []byte
)

func file_metacensus_v1_prop_proto_rawDescGZIP() []byte {
	file_metacensus_v1_prop_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_prop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_prop_proto_rawDesc), len(file_metacensus_v1_prop_proto_rawDesc)))
	})
	return file_metacensus_v1_prop_proto_rawDescData
}

var file_metacensus_v1_prop_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metacensus_v1_prop_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_metacensus_v1_prop_proto_goTypes = []any{
	(PropContent_Type)(0),         // 0: metacensus.v1.PropContent.Type
	(VoteContent_Position)(0),     // 1: metacensus.v1.VoteContent.Position
	(*Prop)(nil),                  // 2: metacensus.v1.Prop
	(*PropContent)(nil),           // 3: metacensus.v1.PropContent
	(*Vote)(nil),                  // 4: metacensus.v1.Vote
	(*VoteContent)(nil),           // 5: metacensus.v1.VoteContent
	(*PropCitation)(nil),          // 6: metacensus.v1.PropCitation
	(*PropListRequest)(nil),       // 7: metacensus.v1.PropListRequest
	(*PropList)(nil),              // 8: metacensus.v1.PropList
	(*PropGetRequest)(nil),        // 9: metacensus.v1.PropGetRequest
	(*PropCreateRequest)(nil),     // 10: metacensus.v1.PropCreateRequest
	(*VoteListRequest)(nil),       // 11: metacensus.v1.VoteListRequest
	(*VoteList)(nil),              // 12: metacensus.v1.VoteList
	(*VoteSetRequest)(nil),        // 13: metacensus.v1.VoteSetRequest
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*UserSignature)(nil),         // 15: metacensus.v1.UserSignature
}
var file_metacensus_v1_prop_proto_depIdxs = []int32{
	14, // 0: metacensus.v1.Prop.recorded:type_name -> google.protobuf.Timestamp
	3,  // 1: metacensus.v1.Prop.content:type_name -> metacensus.v1.PropContent
	15, // 2: metacensus.v1.Prop.user_signature:type_name -> metacensus.v1.UserSignature
	0,  // 3: metacensus.v1.PropContent.type:type_name -> metacensus.v1.PropContent.Type
	14, // 4: metacensus.v1.Vote.recorded:type_name -> google.protobuf.Timestamp
	5,  // 5: metacensus.v1.Vote.content:type_name -> metacensus.v1.VoteContent
	15, // 6: metacensus.v1.Vote.user_signature:type_name -> metacensus.v1.UserSignature
	1,  // 7: metacensus.v1.VoteContent.position:type_name -> metacensus.v1.VoteContent.Position
	6,  // 8: metacensus.v1.VoteContent.citations:type_name -> metacensus.v1.PropCitation
	2,  // 9: metacensus.v1.PropList.items:type_name -> metacensus.v1.Prop
	3,  // 10: metacensus.v1.PropCreateRequest.content:type_name -> metacensus.v1.PropContent
	15, // 11: metacensus.v1.PropCreateRequest.user_signature:type_name -> metacensus.v1.UserSignature
	4,  // 12: metacensus.v1.VoteList.items:type_name -> metacensus.v1.Vote
	5,  // 13: metacensus.v1.VoteSetRequest.content:type_name -> metacensus.v1.VoteContent
	15, // 14: metacensus.v1.VoteSetRequest.user_signature:type_name -> metacensus.v1.UserSignature
	7,  // 15: metacensus.v1.PropRoutes.ListProps:input_type -> metacensus.v1.PropListRequest
	9,  // 16: metacensus.v1.PropRoutes.GetProp:input_type -> metacensus.v1.PropGetRequest
	10, // 17: metacensus.v1.PropRoutes.CreateProp:input_type -> metacensus.v1.PropCreateRequest
	11, // 18: metacensus.v1.PropRoutes.ListVotes:input_type -> metacensus.v1.VoteListRequest
	13, // 19: metacensus.v1.PropRoutes.SetVote:input_type -> metacensus.v1.VoteSetRequest
	8,  // 20: metacensus.v1.PropRoutes.ListProps:output_type -> metacensus.v1.PropList
	2,  // 21: metacensus.v1.PropRoutes.GetProp:output_type -> metacensus.v1.Prop
	2,  // 22: metacensus.v1.PropRoutes.CreateProp:output_type -> metacensus.v1.Prop
	12, // 23: metacensus.v1.PropRoutes.ListVotes:output_type -> metacensus.v1.VoteList
	4,  // 24: metacensus.v1.PropRoutes.SetVote:output_type -> metacensus.v1.Vote
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_metacensus_v1_prop_proto_init() }
func file_metacensus_v1_prop_proto_init() {
	if File_metacensus_v1_prop_proto != nil {
		return
	}
	file_metacensus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_prop_proto_rawDesc), len(file_metacensus_v1_prop_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metacensus_v1_prop_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_prop_proto_depIdxs,
		EnumInfos:         file_metacensus_v1_prop_proto_enumTypes,
		MessageInfos:      file_metacensus_v1_prop_proto_msgTypes,
	}.Build()
	File_metacensus_v1_prop_proto = out.File
	file_metacensus_v1_prop_proto_goTypes = nil
	file_metacensus_v1_prop_proto_depIdxs = nil
}
