// Propositions and votes: the consensus mechanism.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metacensus/v1/prop.proto

package metacensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type is what the proposition would do if it passed.
//
// These are exactly infra's `propType` values, and exactly the union in
// `types/Prop.ts`. demo stores the discriminant as free text defaulting to
// `"Statement"` and validates nothing.
//
// SOURCE CONFLICT: infra names its zero value `Undefined` and emits that
// string. The contract's zero value is `Unspecified`, which is a
// wire-visible rename for infra.
//
// Only `Statement` and `TopicQuestion` are ever created today: the SPA's two
// creation forms send those. The other five are declared by infra's chaincode
// and by `types/Prop.ts` but nothing constructs them.
type Prop_Type int32

const (
	Prop_Unspecified              Prop_Type = 0
	Prop_Statement                Prop_Type = 1
	Prop_TopicQuestion            Prop_Type = 2
	Prop_TopicChange              Prop_Type = 3
	Prop_UserAdmit                Prop_Type = 4
	Prop_UserExpulse              Prop_Type = 5
	Prop_PaperExtractionComplete  Prop_Type = 6
	Prop_PaperIncludeMetaAnalysis Prop_Type = 7
)

// Enum value maps for Prop_Type.
var (
	Prop_Type_name = map[int32]string{
		0: "Unspecified",
		1: "Statement",
		2: "TopicQuestion",
		3: "TopicChange",
		4: "UserAdmit",
		5: "UserExpulse",
		6: "PaperExtractionComplete",
		7: "PaperIncludeMetaAnalysis",
	}
	Prop_Type_value = map[string]int32{
		"Unspecified":              0,
		"Statement":                1,
		"TopicQuestion":            2,
		"TopicChange":              3,
		"UserAdmit":                4,
		"UserExpulse":              5,
		"PaperExtractionComplete":  6,
		"PaperIncludeMetaAnalysis": 7,
	}
)

func (x Prop_Type) Enum() *Prop_Type {
	p := new(Prop_Type)
	*p = x
	return p
}

func (x Prop_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Prop_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_metacensus_v1_prop_proto_enumTypes[0].Descriptor()
}

func (Prop_Type) Type() protoreflect.EnumType {
	return &file_metacensus_v1_prop_proto_enumTypes[0]
}

func (x Prop_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Prop_Type.Descriptor instead.
func (Prop_Type) EnumDescriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{0, 0}
}

type PropConclusion_Value int32

const (
	PropConclusion_Unspecified PropConclusion_Value = 0
	PropConclusion_Open        PropConclusion_Value = 1
	PropConclusion_Passed      PropConclusion_Value = 2
	PropConclusion_Failed      PropConclusion_Value = 3
	PropConclusion_Expired     PropConclusion_Value = 4
)

// Enum value maps for PropConclusion_Value.
var (
	PropConclusion_Value_name = map[int32]string{
		0: "Unspecified",
		1: "Open",
		2: "Passed",
		3: "Failed",
		4: "Expired",
	}
	PropConclusion_Value_value = map[string]int32{
		"Unspecified": 0,
		"Open":        1,
		"Passed":      2,
		"Failed":      3,
		"Expired":     4,
	}
)

func (x PropConclusion_Value) Enum() *PropConclusion_Value {
	p := new(PropConclusion_Value)
	*p = x
	return p
}

func (x PropConclusion_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropConclusion_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_metacensus_v1_prop_proto_enumTypes[1].Descriptor()
}

func (PropConclusion_Value) Type() protoreflect.EnumType {
	return &file_metacensus_v1_prop_proto_enumTypes[1]
}

func (x PropConclusion_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropConclusion_Value.Descriptor instead.
func (PropConclusion_Value) EnumDescriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{1, 0}
}

// Position is which way the member voted.
//
// `For`/`Against`/`Abstain` come from infra's `position` stringer and from
// `types/vote.ts`.
//
// SOURCE CONFLICT: demo stores `"agree" | "disagree" | "abstain"` in its
// `vote.value` column and translates at the edge — its route file carries
// `POSITION_TO_VALUE` and `VALUE_TO_POSITION` maps for exactly this. Its
// create handler accepts either vocabulary in the request body. The contract
// is the `For`/`Against`/`Abstain` vocabulary, matching two sources of three
// and the values the SPA sends.
//
// SOURCE CONFLICT: infra's zero value is named `Undefined`.
type Vote_Position int32

const (
	Vote_Unspecified Vote_Position = 0
	Vote_For         Vote_Position = 1
	Vote_Against     Vote_Position = 2
	Vote_Abstain     Vote_Position = 3
)

// Enum value maps for Vote_Position.
var (
	Vote_Position_name = map[int32]string{
		0: "Unspecified",
		1: "For",
		2: "Against",
		3: "Abstain",
	}
	Vote_Position_value = map[string]int32{
		"Unspecified": 0,
		"For":         1,
		"Against":     2,
		"Abstain":     3,
	}
)

func (x Vote_Position) Enum() *Vote_Position {
	p := new(Vote_Position)
	*p = x
	return p
}

func (x Vote_Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vote_Position) Descriptor() protoreflect.EnumDescriptor {
	return file_metacensus_v1_prop_proto_enumTypes[2].Descriptor()
}

func (Vote_Position) Type() protoreflect.EnumType {
	return &file_metacensus_v1_prop_proto_enumTypes[2]
}

func (x Vote_Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vote_Position.Descriptor instead.
func (Vote_Position) EnumDescriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{2, 0}
}

// Prop is a motion a topic's members vote on.
//
// infra is the authority on what a prop *is*: "Propositions can be both
// functional and non-functional, causing changes to a topic or simply
// establishing consensus amongst members". demo persists props in a table
// called `consensus_statements` — the name predates props being general — with
// a `type` discriminant added so the SPA can tell a consensus statement from a
// meta-analysis question.
//
// The SPA reaches this resource through hardcoded paths:
// `${routes.api.topic}/${topicId}/prop`. Neither `/topic/{id}/prop` nor
// `/topic/{id}/prop/{propId}/vote` appears in `src/lib/routes.ts`, despite that
// file's instruction never to hardcode a path at a call site. They are served
// by both backends and are part of the surface.
type Prop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// SOURCE CONFLICT: demo emits `topicId`; infra's `Prop` has no topic field at
	// all — the topic is in the path and the prop is stored under the topic's
	// ledger scope. Kept because the SPA receives lists of props detached from
	// their request context.
	TopicId  string `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	AuthorId string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// `created`, not `createdAt`: all three sources agree here.
	Created *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Type    Prop_Type              `protobuf:"varint,5,opt,name=type,proto3,enum=metacensus.v1.Prop_Type" json:"type,omitempty"`
	// The text of the proposition.
	//
	// SOURCE CONFLICT: demo's column is `statement` and its create handler
	// accepts any of `description`, `statement` or `text` in the body before
	// emitting it as `description`. The SPA sends `description`; infra reads
	// `description`. The contract is `description` and demo's leniency is not
	// part of it.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// When voting closed. Absent while the prop is open.
	//
	// SOURCE CONFLICT: `types/Prop.ts` declares `concluded: string` and demo
	// emits the empty string `""` unconditionally — which is not a valid RFC 3339
	// timestamp and would fail to parse. Modelling it as a `Timestamp` makes
	// "still open" an absent field instead of an unparseable one.
	Concluded *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=concluded,proto3" json:"concluded,omitempty"`
	// The outcome. See `PropConclusion`.
	Conclusion PropConclusion_Value `protobuf:"varint,8,opt,name=conclusion,proto3,enum=metacensus.v1.PropConclusion_Value" json:"conclusion,omitempty"`
	// The votes cast, embedded.
	//
	// SOURCE CONFLICT: infra's chaincode assembles this on every read — `Get` and
	// `GetAll` both call `GetAllVotes` per prop and attach the result. demo never
	// populates it; the SPA fetches votes separately from
	// `/topic/{id}/prop/{propId}/vote`. Kept because infra is the authority on
	// domain semantics and a prop without its votes is half a record, but a
	// backend that finds the join expensive may leave it empty and serve the
	// vote endpoint instead.
	Votes         []*Vote `protobuf:"bytes,9,rep,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prop) Reset() {
	*x = Prop{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prop) ProtoMessage() {}

func (x *Prop) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prop.ProtoReflect.Descriptor instead.
func (*Prop) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{0}
}

func (x *Prop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Prop) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *Prop) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Prop) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Prop) GetType() Prop_Type {
	if x != nil {
		return x.Type
	}
	return Prop_Unspecified
}

func (x *Prop) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Prop) GetConcluded() *timestamppb.Timestamp {
	if x != nil {
		return x.Concluded
	}
	return nil
}

func (x *Prop) GetConclusion() PropConclusion_Value {
	if x != nil {
		return x.Conclusion
	}
	return PropConclusion_Unspecified
}

func (x *Prop) GetVotes() []*Vote {
	if x != nil {
		return x.Votes
	}
	return nil
}

// PropConclusion wraps the conclusion vocabulary.
//
// It is a wrapper message rather than a second enum nested in `Prop` because
// protobuf scopes enum value names to the *parent* message, C++ style, not to
// the enum. `Prop.Type` and a `Prop.Conclusion` would both contribute an
// `Unspecified` constant to `Prop`'s scope and fail to compile. This is the one
// place in the contract where that bites; every other enum is nested in the
// message that owns it.
//
// SOURCE CONFLICT: `types/Prop.ts` spells these lowercase —
// `"open" | "passed" | "failed" | "expired"` — and demo stores `"open"` as its
// default `status`, mapping it into `conclusion` on the way out. infra has no
// conclusion field: a prop is never concluded on chain. PascalCase here follows
// the enum convention, so adopting it changes demo's stored values and the SPA's
// comparisons (`p.conclusion === "open"`).
type PropConclusion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropConclusion) Reset() {
	*x = PropConclusion{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropConclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropConclusion) ProtoMessage() {}

func (x *PropConclusion) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropConclusion.ProtoReflect.Descriptor instead.
func (*PropConclusion) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{1}
}

// Vote is one member's position on one prop.
//
// Votes are overwritten, not appended: demo has a `(propId, userId)` unique
// index and upserts, and infra's chaincode merges the new vote into the stored
// one with `OverwriteWith`. There is no vote history in either backend, which
// is why `last_cast` is named for the most recent cast rather than a creation
// time.
type Vote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SOURCE CONFLICT: demo emits an `id` (its serial, stringified);
	// `types/vote.ts` declares no id; infra's `VoteSetResponse` returns a
	// *composite* `DuoId` — `{prefix: "vote", id1: <propId>, id2: <userId>}` — an
	// object, not a string. Ids are strings on the wire, so infra's composite has
	// to be flattened before it reaches a client.
	Id       string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PropId   string        `protobuf:"bytes,2,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	UserId   string        `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Position Vote_Position `protobuf:"varint,4,opt,name=position,proto3,enum=metacensus.v1.Vote_Position" json:"position,omitempty"`
	// Free-text rationale. Marked `// TODO, is this temp?` in infra, and required
	// by nothing.
	Explanation string `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// Character offsets into the prop's `description` that the voter highlighted.
	//
	// Domain rule, from infra's chaincode: citations are meaningful only for an
	// `Against` vote. `types.NewVote` clears them for `For` and `Abstain`, and
	// `OverwriteWith` clears them again on any change to those positions. The SPA
	// enforces the same rule client-side. demo stores whatever it is given.
	Citations []*PropCitation `protobuf:"bytes,6,rep,name=citations,proto3" json:"citations,omitempty"`
	// When the vote was most recently cast. Overwritten on every recast.
	LastCast      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_cast,json=lastCast,proto3" json:"last_cast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{2}
}

func (x *Vote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vote) GetPropId() string {
	if x != nil {
		return x.PropId
	}
	return ""
}

func (x *Vote) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Vote) GetPosition() Vote_Position {
	if x != nil {
		return x.Position
	}
	return Vote_Unspecified
}

func (x *Vote) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Vote) GetCitations() []*PropCitation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *Vote) GetLastCast() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCast
	}
	return nil
}

// PropCitation is a half-open character range in a prop's `description`.
type PropCitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropCitation) Reset() {
	*x = PropCitation{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropCitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropCitation) ProtoMessage() {}

func (x *PropCitation) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropCitation.ProtoReflect.Descriptor instead.
func (*PropCitation) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{3}
}

func (x *PropCitation) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PropCitation) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// PropListRequest is the path parameter of `GET /topic/{topicId}/prop`.
type PropListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropListRequest) Reset() {
	*x = PropListRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropListRequest) ProtoMessage() {}

func (x *PropListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropListRequest.ProtoReflect.Descriptor instead.
func (*PropListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{4}
}

func (x *PropListRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// PropList is the response to `GET /topic/{topicId}/prop`.
//
// SOURCE CONFLICT: both backends return a bare JSON array — infra goes out of
// its way to, with an explicit "Ensure we always return a JSON array (`[]`)
// instead of `null`". Wrapping is a wire break for both.
type PropList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Prop                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropList) Reset() {
	*x = PropList{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropList) ProtoMessage() {}

func (x *PropList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropList.ProtoReflect.Descriptor instead.
func (*PropList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{5}
}

func (x *PropList) GetItems() []*Prop {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PropList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PropGetRequest is the path parameters of
// `GET /topic/{topicId}/prop/{propId}`, which returns a `Prop` bare.
//
// infra only; demo has no per-prop read and the SPA finds a prop by filtering
// the list.
//
// SOURCE CONFLICT: infra wraps it in `{"prop": {...}}` (its `PropGetResponse`).
// Single-resource reads return the resource bare.
type PropGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PropId        string                 `protobuf:"bytes,2,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropGetRequest) Reset() {
	*x = PropGetRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropGetRequest) ProtoMessage() {}

func (x *PropGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropGetRequest.ProtoReflect.Descriptor instead.
func (*PropGetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{6}
}

func (x *PropGetRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *PropGetRequest) GetPropId() string {
	if x != nil {
		return x.PropId
	}
	return ""
}

// PropCreateRequest is the body of `POST /topic/{topicId}/prop`.
//
// The author is the authenticated user; both backends take it from the token
// and neither accepts it in the body. demo strips any client-supplied
// `x-user-id` header for the same reason.
type PropCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Prop_Type              `protobuf:"varint,1,opt,name=type,proto3,enum=metacensus.v1.Prop_Type" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropCreateRequest) Reset() {
	*x = PropCreateRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropCreateRequest) ProtoMessage() {}

func (x *PropCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropCreateRequest.ProtoReflect.Descriptor instead.
func (*PropCreateRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{7}
}

func (x *PropCreateRequest) GetType() Prop_Type {
	if x != nil {
		return x.Type
	}
	return Prop_Unspecified
}

func (x *PropCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// VoteListRequest is the path parameters of
// `GET /topic/{topicId}/prop/{propId}/vote`.
type VoteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	PropId        string                 `protobuf:"bytes,2,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteListRequest) Reset() {
	*x = VoteListRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteListRequest) ProtoMessage() {}

func (x *VoteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteListRequest.ProtoReflect.Descriptor instead.
func (*VoteListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{8}
}

func (x *VoteListRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *VoteListRequest) GetPropId() string {
	if x != nil {
		return x.PropId
	}
	return ""
}

// VoteList is the response to `GET /topic/{topicId}/prop/{propId}/vote`.
//
// SOURCE CONFLICT: demo returns a bare JSON array. infra does not route this
// method at all — it declares `VoteGet`/`VoteGetAll` on its `DataSource`
// interface and leaves both commented out — so a vote list is reachable only
// via the `votes` embedded in a prop. Both paths should exist.
type VoteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Vote                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteList) Reset() {
	*x = VoteList{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteList) ProtoMessage() {}

func (x *VoteList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteList.ProtoReflect.Descriptor instead.
func (*VoteList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{9}
}

func (x *VoteList) GetItems() []*Vote {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *VoteList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// VoteSetRequest is the body of `POST /topic/{topicId}/prop/{propId}/vote`.
//
// Set, not create: a second call from the same user replaces the first.
//
// SOURCE CONFLICT: demo also accepts `{"value": "agree"}` as an alternative to
// `{"position": "For"}`. Only `position` is in the contract.
type VoteSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      Vote_Position          `protobuf:"varint,1,opt,name=position,proto3,enum=metacensus.v1.Vote_Position" json:"position,omitempty"`
	Explanation   string                 `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Citations     []*PropCitation        `protobuf:"bytes,3,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteSetRequest) Reset() {
	*x = VoteSetRequest{}
	mi := &file_metacensus_v1_prop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteSetRequest) ProtoMessage() {}

func (x *VoteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_prop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteSetRequest.ProtoReflect.Descriptor instead.
func (*VoteSetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_prop_proto_rawDescGZIP(), []int{10}
}

func (x *VoteSetRequest) GetPosition() Vote_Position {
	if x != nil {
		return x.Position
	}
	return Vote_Unspecified
}

func (x *VoteSetRequest) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *VoteSetRequest) GetCitations() []*PropCitation {
	if x != nil {
		return x.Citations
	}
	return nil
}

var File_metacensus_v1_prop_proto protoreflect.FileDescriptor

const file_metacensus_v1_prop_proto_rawDesc = "" +
	"\n" +
	"\x18metacensus/v1/prop.proto\x12\rmetacensus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametacensus/v1/common.proto\"\xa6\x04\n" +
	"\x04Prop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12,\n" +
	"\x04type\x18\x05 \x01(\x0e2\x18.metacensus.v1.Prop.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x128\n" +
	"\tconcluded\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tconcluded\x12C\n" +
	"\n" +
	"conclusion\x18\b \x01(\x0e2#.metacensus.v1.PropConclusion.ValueR\n" +
	"conclusion\x12)\n" +
	"\x05votes\x18\t \x03(\v2\x13.metacensus.v1.VoteR\x05votes\"\xa5\x01\n" +
	"\x04Type\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\r\n" +
	"\tStatement\x10\x01\x12\x11\n" +
	"\rTopicQuestion\x10\x02\x12\x0f\n" +
	"\vTopicChange\x10\x03\x12\r\n" +
	"\tUserAdmit\x10\x04\x12\x0f\n" +
	"\vUserExpulse\x10\x05\x12\x1b\n" +
	"\x17PaperExtractionComplete\x10\x06\x12\x1c\n" +
	"\x18PaperIncludeMetaAnalysis\x10\a\"Y\n" +
	"\x0ePropConclusion\"G\n" +
	"\x05Value\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\b\n" +
	"\x04Open\x10\x01\x12\n" +
	"\n" +
	"\x06Passed\x10\x02\x12\n" +
	"\n" +
	"\x06Failed\x10\x03\x12\v\n" +
	"\aExpired\x10\x04\"\xd8\x02\n" +
	"\x04Vote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aprop_id\x18\x02 \x01(\tR\x06propId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x128\n" +
	"\bposition\x18\x04 \x01(\x0e2\x1c.metacensus.v1.Vote.PositionR\bposition\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x129\n" +
	"\tcitations\x18\x06 \x03(\v2\x1b.metacensus.v1.PropCitationR\tcitations\x127\n" +
	"\tlast_cast\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastCast\">\n" +
	"\bPosition\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\a\n" +
	"\x03For\x10\x01\x12\v\n" +
	"\aAgainst\x10\x02\x12\v\n" +
	"\aAbstain\x10\x03\"6\n" +
	"\fPropCitation\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\",\n" +
	"\x0fPropListRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"n\n" +
	"\bPropList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.metacensus.v1.PropR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\"D\n" +
	"\x0ePropGetRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\aprop_id\x18\x02 \x01(\tR\x06propId\"c\n" +
	"\x11PropCreateRequest\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.metacensus.v1.Prop.TypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"E\n" +
	"\x0fVoteListRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\aprop_id\x18\x02 \x01(\tR\x06propId\"n\n" +
	"\bVoteList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.metacensus.v1.VoteR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\"\xa7\x01\n" +
	"\x0eVoteSetRequest\x128\n" +
	"\bposition\x18\x01 \x01(\x0e2\x1c.metacensus.v1.Vote.PositionR\bposition\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation\x129\n" +
	"\tcitations\x18\x03 \x03(\v2\x1b.metacensus.v1.PropCitationR\tcitationsBAZ?github.com/metacensus/ui/contract/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_prop_proto_rawDescOnce sync.Once
	file_metacensus_v1_prop_proto_rawDescData []byte
)

func file_metacensus_v1_prop_proto_rawDescGZIP() []byte {
	file_metacensus_v1_prop_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_prop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_prop_proto_rawDesc), len(file_metacensus_v1_prop_proto_rawDesc)))
	})
	return file_metacensus_v1_prop_proto_rawDescData
}

var file_metacensus_v1_prop_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_metacensus_v1_prop_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_metacensus_v1_prop_proto_goTypes = []any{
	(Prop_Type)(0),                // 0: metacensus.v1.Prop.Type
	(PropConclusion_Value)(0),     // 1: metacensus.v1.PropConclusion.Value
	(Vote_Position)(0),            // 2: metacensus.v1.Vote.Position
	(*Prop)(nil),                  // 3: metacensus.v1.Prop
	(*PropConclusion)(nil),        // 4: metacensus.v1.PropConclusion
	(*Vote)(nil),                  // 5: metacensus.v1.Vote
	(*PropCitation)(nil),          // 6: metacensus.v1.PropCitation
	(*PropListRequest)(nil),       // 7: metacensus.v1.PropListRequest
	(*PropList)(nil),              // 8: metacensus.v1.PropList
	(*PropGetRequest)(nil),        // 9: metacensus.v1.PropGetRequest
	(*PropCreateRequest)(nil),     // 10: metacensus.v1.PropCreateRequest
	(*VoteListRequest)(nil),       // 11: metacensus.v1.VoteListRequest
	(*VoteList)(nil),              // 12: metacensus.v1.VoteList
	(*VoteSetRequest)(nil),        // 13: metacensus.v1.VoteSetRequest
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*ListMetadata)(nil),          // 15: metacensus.v1.ListMetadata
}
var file_metacensus_v1_prop_proto_depIdxs = []int32{
	14, // 0: metacensus.v1.Prop.created:type_name -> google.protobuf.Timestamp
	0,  // 1: metacensus.v1.Prop.type:type_name -> metacensus.v1.Prop.Type
	14, // 2: metacensus.v1.Prop.concluded:type_name -> google.protobuf.Timestamp
	1,  // 3: metacensus.v1.Prop.conclusion:type_name -> metacensus.v1.PropConclusion.Value
	5,  // 4: metacensus.v1.Prop.votes:type_name -> metacensus.v1.Vote
	2,  // 5: metacensus.v1.Vote.position:type_name -> metacensus.v1.Vote.Position
	6,  // 6: metacensus.v1.Vote.citations:type_name -> metacensus.v1.PropCitation
	14, // 7: metacensus.v1.Vote.last_cast:type_name -> google.protobuf.Timestamp
	3,  // 8: metacensus.v1.PropList.items:type_name -> metacensus.v1.Prop
	15, // 9: metacensus.v1.PropList.metadata:type_name -> metacensus.v1.ListMetadata
	0,  // 10: metacensus.v1.PropCreateRequest.type:type_name -> metacensus.v1.Prop.Type
	5,  // 11: metacensus.v1.VoteList.items:type_name -> metacensus.v1.Vote
	15, // 12: metacensus.v1.VoteList.metadata:type_name -> metacensus.v1.ListMetadata
	2,  // 13: metacensus.v1.VoteSetRequest.position:type_name -> metacensus.v1.Vote.Position
	6,  // 14: metacensus.v1.VoteSetRequest.citations:type_name -> metacensus.v1.PropCitation
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_metacensus_v1_prop_proto_init() }
func file_metacensus_v1_prop_proto_init() {
	if File_metacensus_v1_prop_proto != nil {
		return
	}
	file_metacensus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_prop_proto_rawDesc), len(file_metacensus_v1_prop_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacensus_v1_prop_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_prop_proto_depIdxs,
		EnumInfos:         file_metacensus_v1_prop_proto_enumTypes,
		MessageInfos:      file_metacensus_v1_prop_proto_msgTypes,
	}.Build()
	File_metacensus_v1_prop_proto = out.File
	file_metacensus_v1_prop_proto_goTypes = nil
	file_metacensus_v1_prop_proto_depIdxs = nil
}
