// Propositions and votes: the consensus mechanism.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: metacensus/v1/prop.proto

package metacensusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropRoutes_ListProps_FullMethodName  = "/metacensus.v1.PropRoutes/ListProps"
	PropRoutes_GetProp_FullMethodName    = "/metacensus.v1.PropRoutes/GetProp"
	PropRoutes_CreateProp_FullMethodName = "/metacensus.v1.PropRoutes/CreateProp"
	PropRoutes_ListVotes_FullMethodName  = "/metacensus.v1.PropRoutes/ListVotes"
	PropRoutes_SetVote_FullMethodName    = "/metacensus.v1.PropRoutes/SetVote"
)

// PropRoutesClient is the client API for PropRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Declared as a gRPC service and served over HTTP by grpc-gateway, which
// transcodes from the google.api.http annotations below. No gRPC server runs.
type PropRoutesClient interface {
	ListProps(ctx context.Context, in *PropListRequest, opts ...grpc.CallOption) (*PropList, error)
	GetProp(ctx context.Context, in *PropGetRequest, opts ...grpc.CallOption) (*Prop, error)
	CreateProp(ctx context.Context, in *PropCreateRequest, opts ...grpc.CallOption) (*Prop, error)
	ListVotes(ctx context.Context, in *VoteListRequest, opts ...grpc.CallOption) (*VoteList, error)
	SetVote(ctx context.Context, in *VoteSetRequest, opts ...grpc.CallOption) (*Vote, error)
}

type propRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewPropRoutesClient(cc grpc.ClientConnInterface) PropRoutesClient {
	return &propRoutesClient{cc}
}

func (c *propRoutesClient) ListProps(ctx context.Context, in *PropListRequest, opts ...grpc.CallOption) (*PropList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropList)
	err := c.cc.Invoke(ctx, PropRoutes_ListProps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propRoutesClient) GetProp(ctx context.Context, in *PropGetRequest, opts ...grpc.CallOption) (*Prop, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prop)
	err := c.cc.Invoke(ctx, PropRoutes_GetProp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propRoutesClient) CreateProp(ctx context.Context, in *PropCreateRequest, opts ...grpc.CallOption) (*Prop, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prop)
	err := c.cc.Invoke(ctx, PropRoutes_CreateProp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propRoutesClient) ListVotes(ctx context.Context, in *VoteListRequest, opts ...grpc.CallOption) (*VoteList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteList)
	err := c.cc.Invoke(ctx, PropRoutes_ListVotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propRoutesClient) SetVote(ctx context.Context, in *VoteSetRequest, opts ...grpc.CallOption) (*Vote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vote)
	err := c.cc.Invoke(ctx, PropRoutes_SetVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropRoutesServer is the server API for PropRoutes service.
// All implementations should embed UnimplementedPropRoutesServer
// for forward compatibility.
//
// Declared as a gRPC service and served over HTTP by grpc-gateway, which
// transcodes from the google.api.http annotations below. No gRPC server runs.
type PropRoutesServer interface {
	ListProps(context.Context, *PropListRequest) (*PropList, error)
	GetProp(context.Context, *PropGetRequest) (*Prop, error)
	CreateProp(context.Context, *PropCreateRequest) (*Prop, error)
	ListVotes(context.Context, *VoteListRequest) (*VoteList, error)
	SetVote(context.Context, *VoteSetRequest) (*Vote, error)
}

// UnimplementedPropRoutesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropRoutesServer struct{}

func (UnimplementedPropRoutesServer) ListProps(context.Context, *PropListRequest) (*PropList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProps not implemented")
}
func (UnimplementedPropRoutesServer) GetProp(context.Context, *PropGetRequest) (*Prop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProp not implemented")
}
func (UnimplementedPropRoutesServer) CreateProp(context.Context, *PropCreateRequest) (*Prop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProp not implemented")
}
func (UnimplementedPropRoutesServer) ListVotes(context.Context, *VoteListRequest) (*VoteList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVotes not implemented")
}
func (UnimplementedPropRoutesServer) SetVote(context.Context, *VoteSetRequest) (*Vote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVote not implemented")
}
func (UnimplementedPropRoutesServer) testEmbeddedByValue() {}

// UnsafePropRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropRoutesServer will
// result in compilation errors.
type UnsafePropRoutesServer interface {
	mustEmbedUnimplementedPropRoutesServer()
}

func RegisterPropRoutesServer(s grpc.ServiceRegistrar, srv PropRoutesServer) {
	// If the following call pancis, it indicates UnimplementedPropRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropRoutes_ServiceDesc, srv)
}

func _PropRoutes_ListProps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropRoutesServer).ListProps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropRoutes_ListProps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropRoutesServer).ListProps(ctx, req.(*PropListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropRoutes_GetProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropRoutesServer).GetProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropRoutes_GetProp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropRoutesServer).GetProp(ctx, req.(*PropGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropRoutes_CreateProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropRoutesServer).CreateProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropRoutes_CreateProp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropRoutesServer).CreateProp(ctx, req.(*PropCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropRoutes_ListVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropRoutesServer).ListVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropRoutes_ListVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropRoutesServer).ListVotes(ctx, req.(*VoteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropRoutes_SetVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropRoutesServer).SetVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropRoutes_SetVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropRoutesServer).SetVote(ctx, req.(*VoteSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropRoutes_ServiceDesc is the grpc.ServiceDesc for PropRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacensus.v1.PropRoutes",
	HandlerType: (*PropRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProps",
			Handler:    _PropRoutes_ListProps_Handler,
		},
		{
			MethodName: "GetProp",
			Handler:    _PropRoutes_GetProp_Handler,
		},
		{
			MethodName: "CreateProp",
			Handler:    _PropRoutes_CreateProp_Handler,
		},
		{
			MethodName: "ListVotes",
			Handler:    _PropRoutes_ListVotes_Handler,
		},
		{
			MethodName: "SetVote",
			Handler:    _PropRoutes_SetVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metacensus/v1/prop.proto",
}
