// Domains and categories: the two flat vocabularies a topic is filed under.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metacensus/v1/taxonomy.proto

package metacensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain is a field of study. `types/Domain.ts` declares `{id, name}`; demo's
// table also carries `createdAt`, `updatedAt` and a `deleted` flag, none of
// which any handler projects away — `POST /domain` returns whole rows.
//
// The contract declares only what the client uses. `deleted` in particular is a
// soft-delete marker that demo never filters on, so `POST /domain` currently
// returns deleted domains; that is a demo bug, not a shape the contract should
// ratify.
type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_taxonomy_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Category is a topic tag. Same story as `Domain`.
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_taxonomy_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DomainListRequest is the body of `POST /domain`.
//
// SOURCE CONFLICT: this is a read served over POST with an ignored body. demo
// registers it as `.post("/domain", ...)` and the SPA calls it with method
// `"POST"` and no body at all. `GET` is the correct method; the contract keeps
// the empty request message so the endpoint has a named shape, and flags the
// method as a thing to fix on adoption. The same applies to `POST /category`
// and `POST /protocol-element`.
type DomainListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainListRequest) Reset() {
	*x = DomainListRequest{}
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainListRequest) ProtoMessage() {}

func (x *DomainListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainListRequest.ProtoReflect.Descriptor instead.
func (*DomainListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_taxonomy_proto_rawDescGZIP(), []int{2}
}

// DomainList is the response to `POST /domain`.
//
// SOURCE CONFLICT: demo returns a bare JSON array.
type DomainList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Domain              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainList) Reset() {
	*x = DomainList{}
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainList) ProtoMessage() {}

func (x *DomainList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainList.ProtoReflect.Descriptor instead.
func (*DomainList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_taxonomy_proto_rawDescGZIP(), []int{3}
}

func (x *DomainList) GetItems() []*Domain {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DomainList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CategoryListRequest is the body of `POST /category`. See `DomainListRequest`.
type CategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_taxonomy_proto_rawDescGZIP(), []int{4}
}

// CategoryList is the response to `POST /category`.
type CategoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryList) Reset() {
	*x = CategoryList{}
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryList) ProtoMessage() {}

func (x *CategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_taxonomy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryList.ProtoReflect.Descriptor instead.
func (*CategoryList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_taxonomy_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryList) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CategoryList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_metacensus_v1_taxonomy_proto protoreflect.FileDescriptor

const file_metacensus_v1_taxonomy_proto_rawDesc = "" +
	"\n" +
	"\x1cmetacensus/v1/taxonomy.proto\x12\rmetacensus.v1\x1a\x1ametacensus/v1/common.proto\",\n" +
	"\x06Domain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x13\n" +
	"\x11DomainListRequest\"r\n" +
	"\n" +
	"DomainList\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.metacensus.v1.DomainR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\"\x15\n" +
	"\x13CategoryListRequest\"v\n" +
	"\fCategoryList\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.metacensus.v1.CategoryR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadataBAZ?github.com/metacensus/ui/contract/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_taxonomy_proto_rawDescOnce sync.Once
	file_metacensus_v1_taxonomy_proto_rawDescData []byte
)

func file_metacensus_v1_taxonomy_proto_rawDescGZIP() []byte {
	file_metacensus_v1_taxonomy_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_taxonomy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_taxonomy_proto_rawDesc), len(file_metacensus_v1_taxonomy_proto_rawDesc)))
	})
	return file_metacensus_v1_taxonomy_proto_rawDescData
}

var file_metacensus_v1_taxonomy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metacensus_v1_taxonomy_proto_goTypes = []any{
	(*Domain)(nil),              // 0: metacensus.v1.Domain
	(*Category)(nil),            // 1: metacensus.v1.Category
	(*DomainListRequest)(nil),   // 2: metacensus.v1.DomainListRequest
	(*DomainList)(nil),          // 3: metacensus.v1.DomainList
	(*CategoryListRequest)(nil), // 4: metacensus.v1.CategoryListRequest
	(*CategoryList)(nil),        // 5: metacensus.v1.CategoryList
	(*ListMetadata)(nil),        // 6: metacensus.v1.ListMetadata
}
var file_metacensus_v1_taxonomy_proto_depIdxs = []int32{
	0, // 0: metacensus.v1.DomainList.items:type_name -> metacensus.v1.Domain
	6, // 1: metacensus.v1.DomainList.metadata:type_name -> metacensus.v1.ListMetadata
	1, // 2: metacensus.v1.CategoryList.items:type_name -> metacensus.v1.Category
	6, // 3: metacensus.v1.CategoryList.metadata:type_name -> metacensus.v1.ListMetadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metacensus_v1_taxonomy_proto_init() }
func file_metacensus_v1_taxonomy_proto_init() {
	if File_metacensus_v1_taxonomy_proto != nil {
		return
	}
	file_metacensus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_taxonomy_proto_rawDesc), len(file_metacensus_v1_taxonomy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacensus_v1_taxonomy_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_taxonomy_proto_depIdxs,
		MessageInfos:      file_metacensus_v1_taxonomy_proto_msgTypes,
	}.Build()
	File_metacensus_v1_taxonomy_proto = out.File
	file_metacensus_v1_taxonomy_proto_goTypes = nil
	file_metacensus_v1_taxonomy_proto_depIdxs = nil
}
