// Topics: the unit of work a group of reviewers organises around.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metacensus/v1/topic.proto

package metacensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Topic is a systematic review in progress.
//
// Four fields, which is both infra's HTTP-facing `apiTopic` and its chaincode
// `Topic` exactly. demo and `types/Topic.ts` describe a record roughly four
// times the size; almost all of the difference is removed here.
//
// The earlier draft took demo's rich shape on the grounds that two sources
// agreed on it. That reasoning does not hold once demo is understood as a
// rapidly-built superset rather than a design: "the client and demo agree" is
// mostly the client having been written against demo's ORM output. What
// remains is what a topic is regardless of implementation — an identified,
// named, described thing that was created at a time.
//
// REMOVED IN THE FIRST PASS
//
//	topicCategories, topicReviewers, topicAdmins, topicContributors —
//	        ORM artifacts, and mostly empty ones. These arrive as
//	        `[{category: {…}}]` rather than `[{…}]` purely because demo's
//	        query projects junction rows that way; `types/Topic.ts` was
//	        written against that output. Worse, only two of the four are ever
//	        written: `POST /topic` inserts `topic_categories` and
//	        `topic_admins`, and no handler anywhere inserts into
//	        `topic_reviewers` or `topic_contributors`, so those two always
//	        come back empty through the API however full the seed data is.
//	        The people on a topic are a membership relation that infra already
//	        routes as `/topic/{topicId}/member`, and modelling the same
//	        information a second way — inline, wrapper-objects, four parallel
//	        lists — is the opposite of elegant. Question: is topic membership
//	        one relation with a role, or four lists? If one, `Member` is where
//	        it belongs and this is the wrong object for it.
//
//	domain — demo-only, and removed together with `POST /domain` and
//	        `POST /category`, which have no infra counterpart at all. A
//	        taxonomy is one design question; splitting it across a topic field
//	        and two endpoints answers it three times. Question: how is a topic
//	        classified, and is that a fixed vocabulary or free tagging?
//
//	status, statusDescription — demo-only free text that neither backend
//	        validates. The five-value enum in the earlier draft was inferred
//	        from the badge-colour map in `types/enums.ts`, which is a styling
//	        table that mixes topic statuses, paper statuses and a prop
//	        conclusion into one flat record. That is not a specification, and
//	        publishing a vocabulary derived from a CSS lookup would freeze a
//	        guess. Question: what is a topic's lifecycle, and is its state
//	        stored or derived from the work done in it?
//
//	question — demo reads and stores it, and the SPA's create form has no
//	        input that sends it, so it is set by nothing. `description`
//	        carries the same information today. Question: does a topic need a
//	        formal research question distinct from its description?
//
//	minimumExtractionReviews — real workflow configuration (how many
//	        independent extractions a paper needs) but it belongs to the
//	        extraction feature, which infra has not built. Removed with the
//	        rest of that feature's uncertainty rather than landing its config
//	        knob first. Question: is the review threshold per topic, per
//	        protocol, or global?
//
//	protocol — demo embeds the whole protocol in every topic, on both the list
//	        and the detail read. `GET /topic/{topicId}/protocol` already
//	        serves it. Embedding it makes every topic list carry every form
//	        definition. Question: none, really — this one is just duplication.
type Topic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SOURCE CONFLICT: demo's topic id is a text UUID from
	// `crypto.randomUUID()` — the one id demo does not serialise as an integer.
	// infra mints `"topc:0192a642-…"`. String either way.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// SOURCE CONFLICT: `types/Topic.ts` declares `created` and infra emits
	// `created`, but demo's column is `createdAt` and its handlers return the row
	// unmapped — so demo serves `createdAt` and the SPA's `Topic.created` is
	// never populated by the backend it actually runs against. `created` matches
	// infra and the client's own declaration; demo has a rename to do.
	Created       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// TopicListRequest is the query string of `GET /topic`.
//
// Empty for the same reason as `UserListRequest`: the only parameters either
// backend takes are `page` and `limit`, and the pagination model is unsettled.
type TopicListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicListRequest) Reset() {
	*x = TopicListRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListRequest) ProtoMessage() {}

func (x *TopicListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListRequest.ProtoReflect.Descriptor instead.
func (*TopicListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{1}
}

// TopicList is the response to `GET /topic`.
//
// SOURCE CONFLICT: demo returns a bare JSON array; infra returns a bare JSON
// array of its four-field `apiTopic`.
type TopicList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Topic               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicList) Reset() {
	*x = TopicList{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicList) ProtoMessage() {}

func (x *TopicList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicList.ProtoReflect.Descriptor instead.
func (*TopicList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{2}
}

func (x *TopicList) GetItems() []*Topic {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TopicList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TopicGetRequest is the path parameter of `GET /topic/{topicId}`, which
// returns a `Topic` bare.
//
// infra maps the literal id `"default"` to a hardcoded topic id seeded by its
// chaincode `InitLedger`, behind a `// TODO remove me after demo`. That alias
// is not part of the contract.
type TopicGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicGetRequest) Reset() {
	*x = TopicGetRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicGetRequest) ProtoMessage() {}

func (x *TopicGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicGetRequest.ProtoReflect.Descriptor instead.
func (*TopicGetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{3}
}

func (x *TopicGetRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// TopicCreateRequest is the body of `POST /topic`.
//
// Exactly what infra reads. demo additionally reads `id`, `question`,
// `minimumExtractionReviews`, `domain`, `categories` and `admins`; all six are
// removed for the reasons given on `Topic`, plus `id` — demo lets a client
// supply the topic's id and infra always mints its own. Letting a caller choose
// a primary key is a decision that needs a reason, and there is no evidence of
// one; the SPA sends no id.
type TopicCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicCreateRequest) Reset() {
	*x = TopicCreateRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicCreateRequest) ProtoMessage() {}

func (x *TopicCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicCreateRequest.ProtoReflect.Descriptor instead.
func (*TopicCreateRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{4}
}

func (x *TopicCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// TopicProtocolRequest is the path parameter of
// `GET /topic/{topicId}/protocol`, which returns the topic's `Protocol` bare.
//
// SOURCE CONFLICT, behavioural: demo's handler binds the path parameter to
// `const _topicId` and then calls `findFirst` with no `where` clause — it
// returns whichever protocol the database hands back first, for every topic.
// That is a bug; the contract's semantics are the ones the route name states.
// infra routes the same path to `handleUnimplemented` (HTTP 501).
type TopicProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicProtocolRequest) Reset() {
	*x = TopicProtocolRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicProtocolRequest) ProtoMessage() {}

func (x *TopicProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicProtocolRequest.ProtoReflect.Descriptor instead.
func (*TopicProtocolRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{5}
}

func (x *TopicProtocolRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// Member is a user's membership of a topic.
//
// UNIMPLEMENTED EVERYWHERE, and kept on purpose. infra routes
// `GET /topic/{topicId}/member` and `GET /topic/{topicId}/member/{userId}` to
// `handleUnimplemented` (HTTP 501); demo has neither route. This is the
// lower-concern kind of gap — the route is declared, it will be designed when
// it is implemented, and the review happens then. It is also the place the four
// removed `Topic` junction lists should end up, so leaving a named home for
// them keeps that connection visible.
//
// The shape is infra's chaincode `types.Member` minus its two accounting
// fields, removed for the same reason as on `User`: `lastActive` and
// `lastCredits` are set once and never updated by anything.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's user id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When they joined the topic.
	Created       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{6}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

// MemberListRequest is the path parameter of `GET /topic/{topicId}/member`.
type MemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberListRequest) Reset() {
	*x = MemberListRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListRequest) ProtoMessage() {}

func (x *MemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListRequest.ProtoReflect.Descriptor instead.
func (*MemberListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{7}
}

func (x *MemberListRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// MemberList is the response to `GET /topic/{topicId}/member`.
type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Member              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{8}
}

func (x *MemberList) GetItems() []*Member {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MemberList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// MemberGetRequest is the path parameters of
// `GET /topic/{topicId}/member/{userId}`, which returns a `Member` bare.
type MemberGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberGetRequest) Reset() {
	*x = MemberGetRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberGetRequest) ProtoMessage() {}

func (x *MemberGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberGetRequest.ProtoReflect.Descriptor instead.
func (*MemberGetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{9}
}

func (x *MemberGetRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *MemberGetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_metacensus_v1_topic_proto protoreflect.FileDescriptor

const file_metacensus_v1_topic_proto_rawDesc = "" +
	"\n" +
	"\x19metacensus/v1/topic.proto\x12\rmetacensus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametacensus/v1/common.proto\"\x83\x01\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x12\n" +
	"\x10TopicListRequest\"p\n" +
	"\tTopicList\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.metacensus.v1.TopicR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\",\n" +
	"\x0fTopicGetRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"J\n" +
	"\x12TopicCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"1\n" +
	"\x14TopicProtocolRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"N\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\".\n" +
	"\x11MemberListRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"r\n" +
	"\n" +
	"MemberList\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.metacensus.v1.MemberR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\"F\n" +
	"\x10MemberGetRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userIdBAZ?github.com/metacensus/ui/contract/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_topic_proto_rawDescOnce sync.Once
	file_metacensus_v1_topic_proto_rawDescData []byte
)

func file_metacensus_v1_topic_proto_rawDescGZIP() []byte {
	file_metacensus_v1_topic_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_topic_proto_rawDesc), len(file_metacensus_v1_topic_proto_rawDesc)))
	})
	return file_metacensus_v1_topic_proto_rawDescData
}

var file_metacensus_v1_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_metacensus_v1_topic_proto_goTypes = []any{
	(*Topic)(nil),                 // 0: metacensus.v1.Topic
	(*TopicListRequest)(nil),      // 1: metacensus.v1.TopicListRequest
	(*TopicList)(nil),             // 2: metacensus.v1.TopicList
	(*TopicGetRequest)(nil),       // 3: metacensus.v1.TopicGetRequest
	(*TopicCreateRequest)(nil),    // 4: metacensus.v1.TopicCreateRequest
	(*TopicProtocolRequest)(nil),  // 5: metacensus.v1.TopicProtocolRequest
	(*Member)(nil),                // 6: metacensus.v1.Member
	(*MemberListRequest)(nil),     // 7: metacensus.v1.MemberListRequest
	(*MemberList)(nil),            // 8: metacensus.v1.MemberList
	(*MemberGetRequest)(nil),      // 9: metacensus.v1.MemberGetRequest
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*ListMetadata)(nil),          // 11: metacensus.v1.ListMetadata
}
var file_metacensus_v1_topic_proto_depIdxs = []int32{
	10, // 0: metacensus.v1.Topic.created:type_name -> google.protobuf.Timestamp
	0,  // 1: metacensus.v1.TopicList.items:type_name -> metacensus.v1.Topic
	11, // 2: metacensus.v1.TopicList.metadata:type_name -> metacensus.v1.ListMetadata
	10, // 3: metacensus.v1.Member.created:type_name -> google.protobuf.Timestamp
	6,  // 4: metacensus.v1.MemberList.items:type_name -> metacensus.v1.Member
	11, // 5: metacensus.v1.MemberList.metadata:type_name -> metacensus.v1.ListMetadata
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_metacensus_v1_topic_proto_init() }
func file_metacensus_v1_topic_proto_init() {
	if File_metacensus_v1_topic_proto != nil {
		return
	}
	file_metacensus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_topic_proto_rawDesc), len(file_metacensus_v1_topic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacensus_v1_topic_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_topic_proto_depIdxs,
		MessageInfos:      file_metacensus_v1_topic_proto_msgTypes,
	}.Build()
	File_metacensus_v1_topic_proto = out.File
	file_metacensus_v1_topic_proto_goTypes = nil
	file_metacensus_v1_topic_proto_depIdxs = nil
}
