// Topics and their membership.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: metacensus/v1/topic.proto

package metacensusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopicRoutes_ListTopics_FullMethodName  = "/metacensus.v1.TopicRoutes/ListTopics"
	TopicRoutes_GetTopic_FullMethodName    = "/metacensus.v1.TopicRoutes/GetTopic"
	TopicRoutes_CreateTopic_FullMethodName = "/metacensus.v1.TopicRoutes/CreateTopic"
	TopicRoutes_GetProtocol_FullMethodName = "/metacensus.v1.TopicRoutes/GetProtocol"
	TopicRoutes_ListMembers_FullMethodName = "/metacensus.v1.TopicRoutes/ListMembers"
	TopicRoutes_GetMember_FullMethodName   = "/metacensus.v1.TopicRoutes/GetMember"
)

// TopicRoutesClient is the client API for TopicRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Declared as a gRPC service and served over HTTP by grpc-gateway, which
// transcodes from the google.api.http annotations below. No gRPC server runs.
type TopicRoutesClient interface {
	ListTopics(ctx context.Context, in *TopicListRequest, opts ...grpc.CallOption) (*TopicList, error)
	GetTopic(ctx context.Context, in *TopicGetRequest, opts ...grpc.CallOption) (*Topic, error)
	CreateTopic(ctx context.Context, in *TopicCreateRequest, opts ...grpc.CallOption) (*Topic, error)
	GetProtocol(ctx context.Context, in *TopicProtocolRequest, opts ...grpc.CallOption) (*Protocol, error)
	ListMembers(ctx context.Context, in *MemberListRequest, opts ...grpc.CallOption) (*MemberList, error)
	GetMember(ctx context.Context, in *MemberGetRequest, opts ...grpc.CallOption) (*Member, error)
}

type topicRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewTopicRoutesClient(cc grpc.ClientConnInterface) TopicRoutesClient {
	return &topicRoutesClient{cc}
}

func (c *topicRoutesClient) ListTopics(ctx context.Context, in *TopicListRequest, opts ...grpc.CallOption) (*TopicList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicList)
	err := c.cc.Invoke(ctx, TopicRoutes_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicRoutesClient) GetTopic(ctx context.Context, in *TopicGetRequest, opts ...grpc.CallOption) (*Topic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Topic)
	err := c.cc.Invoke(ctx, TopicRoutes_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicRoutesClient) CreateTopic(ctx context.Context, in *TopicCreateRequest, opts ...grpc.CallOption) (*Topic, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Topic)
	err := c.cc.Invoke(ctx, TopicRoutes_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicRoutesClient) GetProtocol(ctx context.Context, in *TopicProtocolRequest, opts ...grpc.CallOption) (*Protocol, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Protocol)
	err := c.cc.Invoke(ctx, TopicRoutes_GetProtocol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicRoutesClient) ListMembers(ctx context.Context, in *MemberListRequest, opts ...grpc.CallOption) (*MemberList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberList)
	err := c.cc.Invoke(ctx, TopicRoutes_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicRoutesClient) GetMember(ctx context.Context, in *MemberGetRequest, opts ...grpc.CallOption) (*Member, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Member)
	err := c.cc.Invoke(ctx, TopicRoutes_GetMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopicRoutesServer is the server API for TopicRoutes service.
// All implementations should embed UnimplementedTopicRoutesServer
// for forward compatibility.
//
// Declared as a gRPC service and served over HTTP by grpc-gateway, which
// transcodes from the google.api.http annotations below. No gRPC server runs.
type TopicRoutesServer interface {
	ListTopics(context.Context, *TopicListRequest) (*TopicList, error)
	GetTopic(context.Context, *TopicGetRequest) (*Topic, error)
	CreateTopic(context.Context, *TopicCreateRequest) (*Topic, error)
	GetProtocol(context.Context, *TopicProtocolRequest) (*Protocol, error)
	ListMembers(context.Context, *MemberListRequest) (*MemberList, error)
	GetMember(context.Context, *MemberGetRequest) (*Member, error)
}

// UnimplementedTopicRoutesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopicRoutesServer struct{}

func (UnimplementedTopicRoutesServer) ListTopics(context.Context, *TopicListRequest) (*TopicList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedTopicRoutesServer) GetTopic(context.Context, *TopicGetRequest) (*Topic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedTopicRoutesServer) CreateTopic(context.Context, *TopicCreateRequest) (*Topic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedTopicRoutesServer) GetProtocol(context.Context, *TopicProtocolRequest) (*Protocol, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProtocol not implemented")
}
func (UnimplementedTopicRoutesServer) ListMembers(context.Context, *MemberListRequest) (*MemberList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedTopicRoutesServer) GetMember(context.Context, *MemberGetRequest) (*Member, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (UnimplementedTopicRoutesServer) testEmbeddedByValue() {}

// UnsafeTopicRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopicRoutesServer will
// result in compilation errors.
type UnsafeTopicRoutesServer interface {
	mustEmbedUnimplementedTopicRoutesServer()
}

func RegisterTopicRoutesServer(s grpc.ServiceRegistrar, srv TopicRoutesServer) {
	// If the following call pancis, it indicates UnimplementedTopicRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopicRoutes_ServiceDesc, srv)
}

func _TopicRoutes_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicRoutesServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicRoutes_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicRoutesServer).ListTopics(ctx, req.(*TopicListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicRoutes_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicRoutesServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicRoutes_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicRoutesServer).GetTopic(ctx, req.(*TopicGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicRoutes_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicRoutesServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicRoutes_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicRoutesServer).CreateTopic(ctx, req.(*TopicCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicRoutes_GetProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicProtocolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicRoutesServer).GetProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicRoutes_GetProtocol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicRoutesServer).GetProtocol(ctx, req.(*TopicProtocolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicRoutes_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicRoutesServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicRoutes_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicRoutesServer).ListMembers(ctx, req.(*MemberListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicRoutes_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicRoutesServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicRoutes_GetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicRoutesServer).GetMember(ctx, req.(*MemberGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopicRoutes_ServiceDesc is the grpc.ServiceDesc for TopicRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopicRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metacensus.v1.TopicRoutes",
	HandlerType: (*TopicRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTopics",
			Handler:    _TopicRoutes_ListTopics_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _TopicRoutes_GetTopic_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _TopicRoutes_CreateTopic_Handler,
		},
		{
			MethodName: "GetProtocol",
			Handler:    _TopicRoutes_GetProtocol_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _TopicRoutes_ListMembers_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _TopicRoutes_GetMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metacensus/v1/topic.proto",
}
