// Topics and their membership.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metacensus/v1/topic.proto

package metacensusv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Topic is a systematic review in progress, as a signed record: the server's
// own fields, the content its author signed, and the signature over it.
type Topic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minted by the server, outside the signature. The topic's address, not part
	// of what it means.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When the server recorded the write; the server's observation, outside the
	// signature. UserSignature.signing_time is the author's claim.
	Recorded      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=recorded,proto3" json:"recorded,omitempty"`
	Content       *TopicContent          `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserSignature *UserSignature         `protobuf:"bytes,4,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetRecorded() *timestamppb.Timestamp {
	if x != nil {
		return x.Recorded
	}
	return nil
}

func (x *Topic) GetContent() *TopicContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Topic) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

// TopicContent is what a topic's author signs. It carries no id: a topic's key
// is minted by the server, and there is no other id in scope here.
type TopicContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicContent) Reset() {
	*x = TopicContent{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicContent) ProtoMessage() {}

func (x *TopicContent) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicContent.ProtoReflect.Descriptor instead.
func (*TopicContent) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{1}
}

func (x *TopicContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicContent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TopicListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicListRequest) Reset() {
	*x = TopicListRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListRequest) ProtoMessage() {}

func (x *TopicListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListRequest.ProtoReflect.Descriptor instead.
func (*TopicListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{2}
}

type TopicList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Topic               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicList) Reset() {
	*x = TopicList{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicList) ProtoMessage() {}

func (x *TopicList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicList.ProtoReflect.Descriptor instead.
func (*TopicList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{3}
}

func (x *TopicList) GetItems() []*Topic {
	if x != nil {
		return x.Items
	}
	return nil
}

type TopicGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicGetRequest) Reset() {
	*x = TopicGetRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicGetRequest) ProtoMessage() {}

func (x *TopicGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicGetRequest.ProtoReflect.Descriptor instead.
func (*TopicGetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{4}
}

func (x *TopicGetRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

type TopicCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *TopicContent          `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	UserSignature *UserSignature         `protobuf:"bytes,2,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicCreateRequest) Reset() {
	*x = TopicCreateRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicCreateRequest) ProtoMessage() {}

func (x *TopicCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicCreateRequest.ProtoReflect.Descriptor instead.
func (*TopicCreateRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{5}
}

func (x *TopicCreateRequest) GetContent() *TopicContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TopicCreateRequest) GetUserSignature() *UserSignature {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

// Member is a user's membership of a topic. No backend implements the member
// routes yet, and no route writes one, so it carries no signature.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's user id, not an id of the membership itself.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When the user joined the topic.
	Joined        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined,proto3" json:"joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{6}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetJoined() *timestamppb.Timestamp {
	if x != nil {
		return x.Joined
	}
	return nil
}

type MemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberListRequest) Reset() {
	*x = MemberListRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberListRequest) ProtoMessage() {}

func (x *MemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberListRequest.ProtoReflect.Descriptor instead.
func (*MemberListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{7}
}

func (x *MemberListRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Member              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{8}
}

func (x *MemberList) GetItems() []*Member {
	if x != nil {
		return x.Items
	}
	return nil
}

type MemberGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberGetRequest) Reset() {
	*x = MemberGetRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberGetRequest) ProtoMessage() {}

func (x *MemberGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberGetRequest.ProtoReflect.Descriptor instead.
func (*MemberGetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{9}
}

func (x *MemberGetRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *MemberGetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_metacensus_v1_topic_proto protoreflect.FileDescriptor

const file_metacensus_v1_topic_proto_rawDesc = "" +
	"\n" +
	"\x19metacensus/v1/topic.proto\x12\rmetacensus.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametacensus/v1/common.proto\"\xd1\x01\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\brecorded\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\brecorded\x125\n" +
	"\acontent\x18\x03 \x01(\v2\x1b.metacensus.v1.TopicContentR\acontent\x12C\n" +
	"\x0euser_signature\x18\x04 \x01(\v2\x1c.metacensus.v1.UserSignatureR\ruserSignatureJ\x04\b\x05\x10\x06\"D\n" +
	"\fTopicContent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x12\n" +
	"\x10TopicListRequest\"7\n" +
	"\tTopicList\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.metacensus.v1.TopicR\x05items\",\n" +
	"\x0fTopicGetRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"\x90\x01\n" +
	"\x12TopicCreateRequest\x125\n" +
	"\acontent\x18\x01 \x01(\v2\x1b.metacensus.v1.TopicContentR\acontent\x12C\n" +
	"\x0euser_signature\x18\x02 \x01(\v2\x1c.metacensus.v1.UserSignatureR\ruserSignature\"L\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06joined\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06joined\".\n" +
	"\x11MemberListRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"9\n" +
	"\n" +
	"MemberList\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.metacensus.v1.MemberR\x05items\"F\n" +
	"\x10MemberGetRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xfd\x03\n" +
	"\vTopicRoutes\x12W\n" +
	"\n" +
	"ListTopics\x12\x1f.metacensus.v1.TopicListRequest\x1a\x18.metacensus.v1.TopicList\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/topic\x12[\n" +
	"\bGetTopic\x12\x1e.metacensus.v1.TopicGetRequest\x1a\x14.metacensus.v1.Topic\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/topic/{topic_id}\x12Y\n" +
	"\vCreateTopic\x12!.metacensus.v1.TopicCreateRequest\x1a\x14.metacensus.v1.Topic\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/topic\x12l\n" +
	"\vListMembers\x12 .metacensus.v1.MemberListRequest\x1a\x19.metacensus.v1.MemberList\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/topic/{topic_id}/member\x12o\n" +
	"\tGetMember\x12\x1f.metacensus.v1.MemberGetRequest\x1a\x15.metacensus.v1.Member\"*\x82\xd3\xe4\x93\x02$\x12\"/topic/{topic_id}/member/{user_id}B9Z7github.com/metacensus/api/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_topic_proto_rawDescOnce sync.Once
	file_metacensus_v1_topic_proto_rawDescData []byte
)

func file_metacensus_v1_topic_proto_rawDescGZIP() []byte {
	file_metacensus_v1_topic_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_topic_proto_rawDesc), len(file_metacensus_v1_topic_proto_rawDesc)))
	})
	return file_metacensus_v1_topic_proto_rawDescData
}

var file_metacensus_v1_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_metacensus_v1_topic_proto_goTypes = []any{
	(*Topic)(nil),                 // 0: metacensus.v1.Topic
	(*TopicContent)(nil),          // 1: metacensus.v1.TopicContent
	(*TopicListRequest)(nil),      // 2: metacensus.v1.TopicListRequest
	(*TopicList)(nil),             // 3: metacensus.v1.TopicList
	(*TopicGetRequest)(nil),       // 4: metacensus.v1.TopicGetRequest
	(*TopicCreateRequest)(nil),    // 5: metacensus.v1.TopicCreateRequest
	(*Member)(nil),                // 6: metacensus.v1.Member
	(*MemberListRequest)(nil),     // 7: metacensus.v1.MemberListRequest
	(*MemberList)(nil),            // 8: metacensus.v1.MemberList
	(*MemberGetRequest)(nil),      // 9: metacensus.v1.MemberGetRequest
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*UserSignature)(nil),         // 11: metacensus.v1.UserSignature
}
var file_metacensus_v1_topic_proto_depIdxs = []int32{
	10, // 0: metacensus.v1.Topic.recorded:type_name -> google.protobuf.Timestamp
	1,  // 1: metacensus.v1.Topic.content:type_name -> metacensus.v1.TopicContent
	11, // 2: metacensus.v1.Topic.user_signature:type_name -> metacensus.v1.UserSignature
	0,  // 3: metacensus.v1.TopicList.items:type_name -> metacensus.v1.Topic
	1,  // 4: metacensus.v1.TopicCreateRequest.content:type_name -> metacensus.v1.TopicContent
	11, // 5: metacensus.v1.TopicCreateRequest.user_signature:type_name -> metacensus.v1.UserSignature
	10, // 6: metacensus.v1.Member.joined:type_name -> google.protobuf.Timestamp
	6,  // 7: metacensus.v1.MemberList.items:type_name -> metacensus.v1.Member
	2,  // 8: metacensus.v1.TopicRoutes.ListTopics:input_type -> metacensus.v1.TopicListRequest
	4,  // 9: metacensus.v1.TopicRoutes.GetTopic:input_type -> metacensus.v1.TopicGetRequest
	5,  // 10: metacensus.v1.TopicRoutes.CreateTopic:input_type -> metacensus.v1.TopicCreateRequest
	7,  // 11: metacensus.v1.TopicRoutes.ListMembers:input_type -> metacensus.v1.MemberListRequest
	9,  // 12: metacensus.v1.TopicRoutes.GetMember:input_type -> metacensus.v1.MemberGetRequest
	3,  // 13: metacensus.v1.TopicRoutes.ListTopics:output_type -> metacensus.v1.TopicList
	0,  // 14: metacensus.v1.TopicRoutes.GetTopic:output_type -> metacensus.v1.Topic
	0,  // 15: metacensus.v1.TopicRoutes.CreateTopic:output_type -> metacensus.v1.Topic
	8,  // 16: metacensus.v1.TopicRoutes.ListMembers:output_type -> metacensus.v1.MemberList
	6,  // 17: metacensus.v1.TopicRoutes.GetMember:output_type -> metacensus.v1.Member
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_metacensus_v1_topic_proto_init() }
func file_metacensus_v1_topic_proto_init() {
	if File_metacensus_v1_topic_proto != nil {
		return
	}
	file_metacensus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_topic_proto_rawDesc), len(file_metacensus_v1_topic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metacensus_v1_topic_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_topic_proto_depIdxs,
		MessageInfos:      file_metacensus_v1_topic_proto_msgTypes,
	}.Build()
	File_metacensus_v1_topic_proto = out.File
	file_metacensus_v1_topic_proto_goTypes = nil
	file_metacensus_v1_topic_proto_depIdxs = nil
}
