// Topics and their membership.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metacensus/v1/topic.proto

package metacensusv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Topic is a systematic review in progress.
type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{1}
}

type TopicList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Topic               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicList) Reset() {
	*x = TopicList{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicList) ProtoMessage() {}

func (x *TopicList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicList.ProtoReflect.Descriptor instead.
func (*TopicList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{2}
}

func (x *TopicList) GetItems() []*Topic {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopicRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolRequest) Reset() {
	*x = GetProtocolRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolRequest) ProtoMessage() {}

func (x *GetProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolRequest.ProtoReflect.Descriptor instead.
func (*GetProtocolRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{5}
}

func (x *GetProtocolRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

// Member is a user's membership of a topic. No backend implements the member
// routes yet.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's user id, not an id of the membership itself.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When the user joined the topic.
	Joined        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined,proto3" json:"joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{6}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetJoined() *timestamppb.Timestamp {
	if x != nil {
		return x.Joined
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{7}
}

func (x *ListMembersRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Member              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{8}
}

func (x *MemberList) GetItems() []*Member {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_metacensus_v1_topic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_topic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_topic_proto_rawDescGZIP(), []int{9}
}

func (x *GetMemberRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *GetMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_metacensus_v1_topic_proto protoreflect.FileDescriptor

const file_metacensus_v1_topic_proto_rawDesc = "" +
	"\n" +
	"\x19metacensus/v1/topic.proto\x12\rmetacensus.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cmetacensus/v1/protocol.proto\"\x83\x01\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\acreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x13\n" +
	"\x11ListTopicsRequest\"7\n" +
	"\tTopicList\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.metacensus.v1.TopicR\x05items\",\n" +
	"\x0fGetTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"J\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"/\n" +
	"\x12GetProtocolRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"L\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06joined\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06joined\"/\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\"9\n" +
	"\n" +
	"MemberList\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.metacensus.v1.MemberR\x05items\"F\n" +
	"\x10GetMemberRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xee\x04\n" +
	"\vTopicRoutes\x12X\n" +
	"\n" +
	"ListTopics\x12 .metacensus.v1.ListTopicsRequest\x1a\x18.metacensus.v1.TopicList\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/topic\x12[\n" +
	"\bGetTopic\x12\x1e.metacensus.v1.GetTopicRequest\x1a\x14.metacensus.v1.Topic\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/topic/{topic_id}\x12Y\n" +
	"\vCreateTopic\x12!.metacensus.v1.CreateTopicRequest\x1a\x14.metacensus.v1.Topic\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/topic\x12m\n" +
	"\vGetProtocol\x12!.metacensus.v1.GetProtocolRequest\x1a\x17.metacensus.v1.Protocol\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/topic/{topic_id}/protocol\x12m\n" +
	"\vListMembers\x12!.metacensus.v1.ListMembersRequest\x1a\x19.metacensus.v1.MemberList\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/topic/{topic_id}/member\x12o\n" +
	"\tGetMember\x12\x1f.metacensus.v1.GetMemberRequest\x1a\x15.metacensus.v1.Member\"*\x82\xd3\xe4\x93\x02$\x12\"/topic/{topic_id}/member/{user_id}B9Z7github.com/metacensus/api/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_topic_proto_rawDescOnce sync.Once
	file_metacensus_v1_topic_proto_rawDescData []byte
)

func file_metacensus_v1_topic_proto_rawDescGZIP() []byte {
	file_metacensus_v1_topic_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_topic_proto_rawDesc), len(file_metacensus_v1_topic_proto_rawDesc)))
	})
	return file_metacensus_v1_topic_proto_rawDescData
}

var file_metacensus_v1_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_metacensus_v1_topic_proto_goTypes = []any{
	(*Topic)(nil),                 // 0: metacensus.v1.Topic
	(*ListTopicsRequest)(nil),     // 1: metacensus.v1.ListTopicsRequest
	(*TopicList)(nil),             // 2: metacensus.v1.TopicList
	(*GetTopicRequest)(nil),       // 3: metacensus.v1.GetTopicRequest
	(*CreateTopicRequest)(nil),    // 4: metacensus.v1.CreateTopicRequest
	(*GetProtocolRequest)(nil),    // 5: metacensus.v1.GetProtocolRequest
	(*Member)(nil),                // 6: metacensus.v1.Member
	(*ListMembersRequest)(nil),    // 7: metacensus.v1.ListMembersRequest
	(*MemberList)(nil),            // 8: metacensus.v1.MemberList
	(*GetMemberRequest)(nil),      // 9: metacensus.v1.GetMemberRequest
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*Protocol)(nil),              // 11: metacensus.v1.Protocol
}
var file_metacensus_v1_topic_proto_depIdxs = []int32{
	10, // 0: metacensus.v1.Topic.created:type_name -> google.protobuf.Timestamp
	0,  // 1: metacensus.v1.TopicList.items:type_name -> metacensus.v1.Topic
	10, // 2: metacensus.v1.Member.joined:type_name -> google.protobuf.Timestamp
	6,  // 3: metacensus.v1.MemberList.items:type_name -> metacensus.v1.Member
	1,  // 4: metacensus.v1.TopicRoutes.ListTopics:input_type -> metacensus.v1.ListTopicsRequest
	3,  // 5: metacensus.v1.TopicRoutes.GetTopic:input_type -> metacensus.v1.GetTopicRequest
	4,  // 6: metacensus.v1.TopicRoutes.CreateTopic:input_type -> metacensus.v1.CreateTopicRequest
	5,  // 7: metacensus.v1.TopicRoutes.GetProtocol:input_type -> metacensus.v1.GetProtocolRequest
	7,  // 8: metacensus.v1.TopicRoutes.ListMembers:input_type -> metacensus.v1.ListMembersRequest
	9,  // 9: metacensus.v1.TopicRoutes.GetMember:input_type -> metacensus.v1.GetMemberRequest
	2,  // 10: metacensus.v1.TopicRoutes.ListTopics:output_type -> metacensus.v1.TopicList
	0,  // 11: metacensus.v1.TopicRoutes.GetTopic:output_type -> metacensus.v1.Topic
	0,  // 12: metacensus.v1.TopicRoutes.CreateTopic:output_type -> metacensus.v1.Topic
	11, // 13: metacensus.v1.TopicRoutes.GetProtocol:output_type -> metacensus.v1.Protocol
	8,  // 14: metacensus.v1.TopicRoutes.ListMembers:output_type -> metacensus.v1.MemberList
	6,  // 15: metacensus.v1.TopicRoutes.GetMember:output_type -> metacensus.v1.Member
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_metacensus_v1_topic_proto_init() }
func file_metacensus_v1_topic_proto_init() {
	if File_metacensus_v1_topic_proto != nil {
		return
	}
	file_metacensus_v1_protocol_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_topic_proto_rawDesc), len(file_metacensus_v1_topic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metacensus_v1_topic_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_topic_proto_depIdxs,
		MessageInfos:      file_metacensus_v1_topic_proto_msgTypes,
	}.Build()
	File_metacensus_v1_topic_proto = out.File
	file_metacensus_v1_topic_proto_goTypes = nil
	file_metacensus_v1_topic_proto_depIdxs = nil
}
