// Users, sessions and identity.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metacensus/v1/user.proto

package metacensusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role is demo's `user.role` column. infra has no notion of a role.
//
// SOURCE CONFLICT: demo stores and filters these lowercase — the SPA calls
// `GET /user?role=admin&limit=100`. The contract's PascalCase spelling is
// required by the enum convention, so adopting it changes both the query
// string and the stored values.
type User_Role int32

const (
	User_Unspecified User_Role = 0
	User_Admin       User_Role = 1
	User_Customer    User_Role = 2
	User_Contributor User_Role = 3
)

// Enum value maps for User_Role.
var (
	User_Role_name = map[int32]string{
		0: "Unspecified",
		1: "Admin",
		2: "Customer",
		3: "Contributor",
	}
	User_Role_value = map[string]int32{
		"Unspecified": 0,
		"Admin":       1,
		"Customer":    2,
		"Contributor": 3,
	}
)

func (x User_Role) Enum() *User_Role {
	p := new(User_Role)
	*p = x
	return p
}

func (x User_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_metacensus_v1_user_proto_enumTypes[0].Descriptor()
}

func (User_Role) Type() protoreflect.EnumType {
	return &file_metacensus_v1_user_proto_enumTypes[0]
}

func (x User_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_Role.Descriptor instead.
func (User_Role) EnumDescriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{0, 0}
}

// User is a MetaCensus account.
//
// This is the widest three-way disagreement in the whole surface. The three
// sources describe three different records:
//
//   - `types/Contributor.ts` declares `{id, name, email, bio, jobTitle,
//     joinedAt, groups[], topics[]}`.
//   - demo returns the `user` table row minus `passwordHash`:
//     `{id, name, email, role, createdAt, updatedAt, jobTitle, bio}`, plus
//     `topicContributors` when the list is filtered to `role=contributor`.
//   - infra returns its ledger `User`: `{id, created, lastActive, lastCredits,
//     name, email, country}`.
//
// Not one field beyond `id`, `name` and `email` is agreed by all three. The
// contract takes the union and records per field which source supplies it,
// because narrowing to the intersection would delete `role` (which `GET /user`
// filters on), `country` (which sign-up collects) and `bio`/`jobTitle` (which
// the contributors table renders).
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SOURCE CONFLICT: demo mints an integer serial, infra mints
	// `"user:0192a642-817d-7a3e-a282-d7a282ebd482"`. String on the wire either
	// way — the contract cannot ratify one backend's format over the other.
	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Collected by the sign-up form and by infra's `POST /user`, stored on
	// infra's ledger `User`. demo accepts it in the sign-up body and then drops
	// it: there is no `country` column on demo's `user` table.
	Country string    `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Role    User_Role `protobuf:"varint,5,opt,name=role,proto3,enum=metacensus.v1.User_Role" json:"role,omitempty"`
	// demo only. `types/Contributor.ts` declares both.
	JobTitle string `protobuf:"bytes,6,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Bio      string `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	// SOURCE CONFLICT: three names for one timestamp. demo emits `createdAt`,
	// infra emits `created`, `types/Contributor.ts` declares `joinedAt`. The
	// contract uses `createdAt`, matching the resource that is actually served
	// to the SPA today.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// demo only.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// infra's ledger accounting. demo has no equivalent columns and never emits
	// these; they arrive only from an infra-backed deployment.
	LastActive  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	LastCredits uint64                 `protobuf:"varint,11,opt,name=last_credits,json=lastCredits,proto3" json:"last_credits,omitempty"`
	// SOURCE CONFLICT: `types/Contributor.ts` declares `groups: {id, name,
	// role}[]`. demo has `group` and `user_groups` tables that model exactly
	// this, but no handler ever joins them into a response, so the SPA's declared
	// field is never populated. Kept because the client declares it and the
	// schema supports it; flagged because nothing serves it.
	Groups []*GroupMembership `protobuf:"bytes,12,rep,name=groups,proto3" json:"groups,omitempty"`
	// demo returns this on `GET /user?role=contributor` only, as
	// `[{topic: <full topic row>}]`.
	//
	// SOURCE CONFLICT: `types/Contributor.ts` declares `topics: string[]` and the
	// contributors table derives it with
	// `item.topicContributors.map(el => el.topic.name)` — i.e. the client's
	// declared type does not match what it actually reads. The contract keeps
	// demo's junction shape (what is served) and narrows the nested topic to a
	// `Reference`, both because the client only reads `topic.name` and because
	// embedding the full `Topic` here would make `user.proto` and `topic.proto`
	// import each other.
	TopicContributors []*UserTopicMembership `protobuf:"bytes,13,rep,name=topic_contributors,json=topicContributors,proto3" json:"topic_contributors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_metacensus_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *User) GetRole() User_Role {
	if x != nil {
		return x.Role
	}
	return User_Unspecified
}

func (x *User) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *User) GetLastCredits() uint64 {
	if x != nil {
		return x.LastCredits
	}
	return 0
}

func (x *User) GetGroups() []*GroupMembership {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *User) GetTopicContributors() []*UserTopicMembership {
	if x != nil {
		return x.TopicContributors
	}
	return nil
}

// GroupMembership is one row of `User.groups`.
type GroupMembership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// demo's `user_groups.role` is its own vocabulary — `"group admin"` or
	// `"contributor"` — and is distinct from `User.Role`. Left as a string
	// because the values contain a space and nothing enumerates them anywhere.
	Role          string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembership) Reset() {
	*x = GroupMembership{}
	mi := &file_metacensus_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembership) ProtoMessage() {}

func (x *GroupMembership) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembership.ProtoReflect.Descriptor instead.
func (*GroupMembership) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMembership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupMembership) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupMembership) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// UserTopicMembership is one row of `User.topic_contributors`.
type UserTopicMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Reference             `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTopicMembership) Reset() {
	*x = UserTopicMembership{}
	mi := &file_metacensus_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTopicMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTopicMembership) ProtoMessage() {}

func (x *UserTopicMembership) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTopicMembership.ProtoReflect.Descriptor instead.
func (*UserTopicMembership) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserTopicMembership) GetTopic() *Reference {
	if x != nil {
		return x.Topic
	}
	return nil
}

// UserReference is a `{id, name, role}` pointer to a user, used where a
// response embeds a person to render their name.
//
// demo's `topicQuery.ts` projects `role` for admins and contributors but not
// for reviewers, and `types/Topic.ts` declares `role` only on contributors. The
// contract carries one shape for all three; `role` is `Unspecified` where the
// backend did not project it.
type UserReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          User_Role              `protobuf:"varint,3,opt,name=role,proto3,enum=metacensus.v1.User_Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReference) Reset() {
	*x = UserReference{}
	mi := &file_metacensus_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReference) ProtoMessage() {}

func (x *UserReference) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReference.ProtoReflect.Descriptor instead.
func (*UserReference) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReference) GetRole() User_Role {
	if x != nil {
		return x.Role
	}
	return User_Unspecified
}

// LoginRequest is the body of `POST /login` (unauthenticated).
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_metacensus_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// SignUpRequest is the body of `POST /user` (unauthenticated).
//
// EXCLUDED FIELD: the SPA also sends `key`, the public half of an ECDSA P-384
// keypair it generates in the browser, exported as a JWK. It is not in this
// message for two reasons. First, JWK member names are fixed by RFC 7517 and
// one of them is `key_ops`; protojson would render a `key_ops` proto field as
// `keyOps`, and the contract does not override field naming. Second, nothing
// consumes it: demo's `SignUpSchema` accepts it, stores it nowhere (there is no
// column), and never verifies the `X-Signature` header the SPA derives from the
// private half. infra has a `// TODO public keys`. Request signing needs a
// design decision before it needs a wire shape.
type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_metacensus_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Session is the response to `POST /login` and to `POST /user` (sign-up).
//
// SOURCE CONFLICT: demo returns `{token, user}`; infra returns `{token}` only,
// because its login handler has the id but not a materialised user. The SPA
// reads `response.token` and nothing else in both cases. The contract keeps
// `user` — a client that has just authenticated should not have to make a
// second call to `/self` to learn who it is — which means infra must populate
// it on adoption.
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_metacensus_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// LogoutResponse is the response to `POST /logout`.
//
// SOURCE CONFLICT: demo returns HTTP 204 with no body at all; infra returns the
// bare JSON string `"logout successful"`, which is not an object. Neither
// satisfies the rule that every response is a JSON object at the root, so the
// contract specifies an empty object, `{}`. This message is deliberately empty
// and is expected to stay that way.
//
// Note that logout is not a session-ending operation in demo: the token stays
// cryptographically valid until it expires. infra genuinely revokes it.
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_metacensus_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{7}
}

// UserListRequest is the query string of `GET /user`.
//
// Not a JSON body — the SPA calls `GET /user?role=admin&limit=100`. It is
// modelled as a message so the parameter set is part of the contract rather
// than folklore.
type UserListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `Unspecified` means "no filter", which is how demo treats a missing
	// `?role=`. The enum is `User.Role` rather than a copy nested here: enum
	// value names are scoped to their parent message, C++ style, so a second
	// `Unspecified` inside `UserListRequest` would be legal but pointlessly
	// duplicative.
	Role          User_Role `protobuf:"varint,1,opt,name=role,proto3,enum=metacensus.v1.User_Role" json:"role,omitempty"`
	Page          int32     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32     `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_metacensus_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserListRequest) GetRole() User_Role {
	if x != nil {
		return x.Role
	}
	return User_Unspecified
}

func (x *UserListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UserList is the response to `GET /user`.
//
// SOURCE CONFLICT: demo returns a bare JSON array. Wrapping it in
// `{items, metadata}` is required by the contract and is a wire break for every
// current caller.
type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*User                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMetadata          `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_metacensus_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserList) GetItems() []*User {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserList) GetMetadata() *ListMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UserGetRequest is the path parameter of `GET /user/{userId}`.
//
// infra only; demo has no per-user read. The SPA does not call it.
type UserGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetRequest) Reset() {
	*x = UserGetRequest{}
	mi := &file_metacensus_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetRequest) ProtoMessage() {}

func (x *UserGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metacensus_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetRequest.ProtoReflect.Descriptor instead.
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return file_metacensus_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserGetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_metacensus_v1_user_proto protoreflect.FileDescriptor

const file_metacensus_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x18metacensus/v1/user.proto\x12\rmetacensus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametacensus/v1/common.proto\"\xdb\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12,\n" +
	"\x04role\x18\x05 \x01(\x0e2\x18.metacensus.v1.User.RoleR\x04role\x12\x1b\n" +
	"\tjob_title\x18\x06 \x01(\tR\bjobTitle\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12;\n" +
	"\vlast_active\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x12!\n" +
	"\flast_credits\x18\v \x01(\x04R\vlastCredits\x126\n" +
	"\x06groups\x18\f \x03(\v2\x1e.metacensus.v1.GroupMembershipR\x06groups\x12Q\n" +
	"\x12topic_contributors\x18\r \x03(\v2\".metacensus.v1.UserTopicMembershipR\x11topicContributors\"A\n" +
	"\x04Role\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\t\n" +
	"\x05Admin\x10\x01\x12\f\n" +
	"\bCustomer\x10\x02\x12\x0f\n" +
	"\vContributor\x10\x03\"I\n" +
	"\x0fGroupMembership\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"E\n" +
	"\x13UserTopicMembership\x12.\n" +
	"\x05topic\x18\x01 \x01(\v2\x18.metacensus.v1.ReferenceR\x05topic\"a\n" +
	"\rUserReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04role\x18\x03 \x01(\x0e2\x18.metacensus.v1.User.RoleR\x04role\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"o\n" +
	"\rSignUpRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"H\n" +
	"\aSession\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12'\n" +
	"\x04user\x18\x02 \x01(\v2\x13.metacensus.v1.UserR\x04user\"\x10\n" +
	"\x0eLogoutResponse\"i\n" +
	"\x0fUserListRequest\x12,\n" +
	"\x04role\x18\x01 \x01(\x0e2\x18.metacensus.v1.User.RoleR\x04role\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"n\n" +
	"\bUserList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.metacensus.v1.UserR\x05items\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.metacensus.v1.ListMetadataR\bmetadata\")\n" +
	"\x0eUserGetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userIdBAZ?github.com/metacensus/ui/contract/go/metacensus/v1;metacensusv1b\x06proto3"

var (
	file_metacensus_v1_user_proto_rawDescOnce sync.Once
	file_metacensus_v1_user_proto_rawDescData []byte
)

func file_metacensus_v1_user_proto_rawDescGZIP() []byte {
	file_metacensus_v1_user_proto_rawDescOnce.Do(func() {
		file_metacensus_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacensus_v1_user_proto_rawDesc), len(file_metacensus_v1_user_proto_rawDesc)))
	})
	return file_metacensus_v1_user_proto_rawDescData
}

var file_metacensus_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metacensus_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_metacensus_v1_user_proto_goTypes = []any{
	(User_Role)(0),                // 0: metacensus.v1.User.Role
	(*User)(nil),                  // 1: metacensus.v1.User
	(*GroupMembership)(nil),       // 2: metacensus.v1.GroupMembership
	(*UserTopicMembership)(nil),   // 3: metacensus.v1.UserTopicMembership
	(*UserReference)(nil),         // 4: metacensus.v1.UserReference
	(*LoginRequest)(nil),          // 5: metacensus.v1.LoginRequest
	(*SignUpRequest)(nil),         // 6: metacensus.v1.SignUpRequest
	(*Session)(nil),               // 7: metacensus.v1.Session
	(*LogoutResponse)(nil),        // 8: metacensus.v1.LogoutResponse
	(*UserListRequest)(nil),       // 9: metacensus.v1.UserListRequest
	(*UserList)(nil),              // 10: metacensus.v1.UserList
	(*UserGetRequest)(nil),        // 11: metacensus.v1.UserGetRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*Reference)(nil),             // 13: metacensus.v1.Reference
	(*ListMetadata)(nil),          // 14: metacensus.v1.ListMetadata
}
var file_metacensus_v1_user_proto_depIdxs = []int32{
	0,  // 0: metacensus.v1.User.role:type_name -> metacensus.v1.User.Role
	12, // 1: metacensus.v1.User.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: metacensus.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: metacensus.v1.User.last_active:type_name -> google.protobuf.Timestamp
	2,  // 4: metacensus.v1.User.groups:type_name -> metacensus.v1.GroupMembership
	3,  // 5: metacensus.v1.User.topic_contributors:type_name -> metacensus.v1.UserTopicMembership
	13, // 6: metacensus.v1.UserTopicMembership.topic:type_name -> metacensus.v1.Reference
	0,  // 7: metacensus.v1.UserReference.role:type_name -> metacensus.v1.User.Role
	1,  // 8: metacensus.v1.Session.user:type_name -> metacensus.v1.User
	0,  // 9: metacensus.v1.UserListRequest.role:type_name -> metacensus.v1.User.Role
	1,  // 10: metacensus.v1.UserList.items:type_name -> metacensus.v1.User
	14, // 11: metacensus.v1.UserList.metadata:type_name -> metacensus.v1.ListMetadata
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_metacensus_v1_user_proto_init() }
func file_metacensus_v1_user_proto_init() {
	if File_metacensus_v1_user_proto != nil {
		return
	}
	file_metacensus_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_v1_user_proto_rawDesc), len(file_metacensus_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacensus_v1_user_proto_goTypes,
		DependencyIndexes: file_metacensus_v1_user_proto_depIdxs,
		EnumInfos:         file_metacensus_v1_user_proto_enumTypes,
		MessageInfos:      file_metacensus_v1_user_proto_msgTypes,
	}.Build()
	File_metacensus_v1_user_proto = out.File
	file_metacensus_v1_user_proto_goTypes = nil
	file_metacensus_v1_user_proto_depIdxs = nil
}
