// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/auth.proto

/* eslint-disable */
import type { Interpretation, Signature, User } from "./common.js";

export const protobufPackage = "metacensus.v1";

/** Sign-up, login and logout. */

export interface LoginRequest {
  email: string;
  password: string;
}

/**
 * Creates an account and enrolls the signing key every later write is
 * signed with: trust on first use — nobody vouches for the key, the service
 * binds whatever it's handed, and the assertion proves possession of the
 * matching private key at enrollment. This is the one write whose key is not
 * resolved from persistence: no account, and so no key history, exists yet.
 */
export interface SignUpRequest {
  content?:
    | User
    | undefined;
  /**
   * Deliberately outside `content`: a password must never be inside a
   * signed, stored document.
   */
  password: string;
  /** How the enrolling assertion is to be read; re-stamped onto the UserSigned. */
  interpretation?:
    | Interpretation
    | undefined;
  /**
   * The public half of the key being enrolled: base64url SPKI DER. Carried
   * here, on the one enrollment write, rather than on every Signature — a
   * usually-empty key field on every record is a footgun (forge content, key
   * and signature and it "verifies"). The store checks `user_signature.key_id`
   * thumbprints this key before binding it. For a passkey this is the public
   * key the navigator.credentials.create() ceremony yielded.
   */
  publicKey: string;
  /**
   * Over `content`, made with the key being enrolled; verified at sign-up
   * against `public_key` (bound by key_id), not against a resolved key.
   */
  userSignature?: Signature | undefined;
}

export interface Session {
  /** Bearer token, sent back as `Authorization: Bearer <token>`. */
  token: string;
}

export interface LogoutRequest {
}

export interface LogoutResponse {
}
