// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/auth.proto

/* eslint-disable */
import type { User, UserSignature } from "./common.js";

export const protobufPackage = "metacensus.v1";

/** Sign-up, login and logout. */

export interface LoginRequest {
  email: string;
  password: string;
}

/**
 * Creates an account and enrolls the signing key every later write is
 * signed with: trust on first use — nobody vouches for the key, the service
 * binds whatever it's handed, and the signature proves possession of the
 * matching private key at enrollment.
 */
export interface SignUpRequest {
  content?:
    | User
    | undefined;
  /**
   * Deliberately outside `content`: a password must never be inside a
   * signed, stored document.
   */
  password: string;
  /**
   * Over `content`, made with the key being enrolled. `signer_id` is empty
   * (no id exists yet) and `public_key` carries the key inline.
   */
  userSignature?: UserSignature | undefined;
}

export interface Session {
  /** Bearer token, sent back as `Authorization: Bearer <token>`. */
  token: string;
}

export interface LogoutRequest {
}

export interface LogoutResponse {
}
