// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/common.proto

/* eslint-disable */

export const protobufPackage = "metacensus.v1";

/** Shared types. */

/** Pagination envelope for list responses; no route paginates yet. */
export interface ListMetadata {
  /** 1-based. */
  page: number;
  limit: number;
  /** Across all pages, not just this one. */
  total: number;
}

export interface HealthcheckRequest {
}

export interface HealthcheckResponse {
  status: string;
}

/**
 * One participant's signature over one content message. Not verified at the
 * API edge — see README.md, "The signing chain".
 */
export interface UserSignature {
  /**
   * Empty only on the sign-up that enrolls the key; public_key carries it
   * inline there instead.
   */
  signerId: string;
  /** base64url SHA-256 of public_key's SPKI DER. */
  keyId: string;
  alg: UserSignature_Alg;
  /** base64url SPKI DER; set only on the sign-up that enrolls the key. */
  publicKey: string;
  /**
   * The signer's claimed time, not the server's — see `recorded` on signed
   * records for what the pair does and does not bound.
   */
  signingTime?:
    | string
    | undefined;
  /**
   * Exactly how this signature is computed and checked; changing the
   * canonicalization, digest, or encoding changes this string.
   */
  spec: string;
  /**
   * Full proto name of the message `content` holds, e.g.
   * "metacensus.v1.Prop". Stops a signature over one type being
   * replayed as another.
   */
  contentType: string;
  /** Excluded from its own digest by being emptied, not dropped. */
  value: string;
}

/**
 * Closed vocabulary: an unrecognized value fails to decode rather than
 * reaching a verifier. See README.md, "The signing chain", before adding one.
 */
export enum UserSignature_Alg {
  Unspecified = "Unspecified",
  /** Es384 - JOSE fixed-width r||s, never DER. */
  Es384 = "Es384",
}

/**
 * An institution's countersignature over a UserSignature.value — it endorses
 * the author (enrolled and in good standing when the record was written), not
 * the content. Server-minted and outside the user's signature, so it rides on
 * the stored envelope and never inside signed content. Computing and checking
 * it is the store's, below the persistence seam; this contract only carries
 * the shape so a later runtime needs no wire break. See README.md.
 */
export interface InstitutionalSignature {
  /** The institution that countersigned. */
  signerId: string;
  /**
   * base64url SHA-256 of the institution key's SPKI DER, resolved against the
   * institution's key history the way a user's key_id is.
   */
  keyId: string;
  /** Reuses UserSignature's closed algorithm vocabulary. */
  alg: UserSignature_Alg;
  /**
   * The server's observation of when it countersigned; the institution makes
   * no separately-claimed time.
   */
  recorded?:
    | string
    | undefined;
  /** Versions the countersignature scheme, independently of UserSignature.spec. */
  spec: string;
  /**
   * base64url r||s over the countersigned UserSignature.value. Emptied from
   * its own digest by the same rule as UserSignature.value.
   */
  value: string;
}

/**
 * The part of a user record its owner signs. Lives here, not user.proto,
 * because auth.proto's SignUpRequest and user.proto's UserSigned both need it.
 */
export interface User {
  name: string;
  email: string;
  country: string;
}
