// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/common.proto

/* eslint-disable */

export const protobufPackage = "metacensus.v1";

/**
 * Shared types. Derivation, exclusions and open questions:
 * contract/DERIVATION.md.
 */

/**
 * ListMetadata is the `metadata` half of every list response. Empty: nothing on
 * this surface paginates. It exists so that a route can grow pagination without
 * breaking consumers, and it is shared by every list, so a field added here is
 * added to all of them.
 */
export interface ListMetadata {
}

/** Error is the body of any failed request. */
export interface Error {
  error: string;
}

/** HealthcheckResponse is the body of `GET /healthcheck`. */
export interface HealthcheckResponse {
  status: string;
}
