// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/common.proto

/* eslint-disable */

export const protobufPackage = "metacensus.v1";

/**
 * Shared types. Derivation, exclusions and open questions:
 * contract/DERIVATION.md.
 */

/**
 * ListMetadata is the pagination envelope for list responses. Defined, but
 * referenced by nothing: no route paginates yet.
 */
export interface ListMetadata {
  /** 1-based. */
  page: number;
  /** Items per page. */
  limit: number;
  /** Items across all pages, not just this one. */
  total: number;
}

/** Error is the body of any failed request. */
export interface Error {
  error: string;
}

/** HealthcheckRequest carries no parameters. */
export interface HealthcheckRequest {
}

export interface HealthcheckResponse {
  status: string;
}
