// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/extraction.proto

/* eslint-disable */

export const protobufPackage = "metacensus.v1";

/** Data extraction: the values pulled from one paper against one protocol. */

/**
 * DataExtraction is the set of values extracted from one paper against one
 * protocol, identified by the three ids together.
 *
 * It is both the body of `POST /extraction`, which upserts it, and what that
 * route and `GET /extraction` return.
 */
export interface DataExtraction {
  topicId: string;
  paperId: string;
  protocolId: string;
  data: DatumExtraction[];
}

/** DatumExtraction is one answered protocol element. */
export interface DatumExtraction {
  protocolElementId: string;
  /**
   * The extracted value. A string for every element type the contract
   * describes; multi-select elements have no representation yet.
   */
  datum: string;
  /**
   * Where in the PDF the value was read from. Empty when the value was typed
   * rather than selected.
   */
  sourceLocation: SourceLocationPage[];
}

/** SourceLocationPage is the highlighted rectangles on one page of a PDF. */
export interface SourceLocationPage {
  page: number;
  rects: SourceRect[];
}

/** SourceRect is one highlight rectangle, in the PDF viewer's coordinate space. */
export interface SourceRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * DataExtractionGetRequest is the query string of `GET /extraction`, which
 * returns a `DataExtraction`. All three fields are required: together they
 * identify it.
 */
export interface DataExtractionGetRequest {
  topicId: string;
  paperId: string;
  protocolId: string;
}
