// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/prop.proto

/* eslint-disable */

export const protobufPackage = "metacensus.v1";

/** Propositions and votes: the consensus mechanism. */

/**
 * Prop is a motion a topic's members vote on. It can be functional, changing
 * the topic, or simply establish consensus.
 */
export interface Prop {
  id: string;
  authorId: string;
  created?: string | undefined;
  type: Prop_Type;
  /** The text of the proposition, and the text `Vote.citations` index into. */
  description: string;
}

/** Type is what the proposition would do if it passed. */
export enum Prop_Type {
  Unspecified = "Unspecified",
  Statement = "Statement",
  TopicQuestion = "TopicQuestion",
  TopicChange = "TopicChange",
  UserAdmit = "UserAdmit",
  UserExpulse = "UserExpulse",
  PaperExtractionComplete = "PaperExtractionComplete",
  PaperIncludeMetaAnalysis = "PaperIncludeMetaAnalysis",
}

/**
 * Vote is one member's position on one prop, keyed by `(propId, userId)`: a
 * second vote from the same user replaces the first rather than adding to it.
 */
export interface Vote {
  propId: string;
  userId: string;
  position: Vote_Position;
  /** Free-text rationale. */
  explanation: string;
  /**
   * Spans of the prop's `description` the voter highlighted. Meaningful only
   * for an `Against` vote; cleared when the position changes to any other.
   */
  citations: PropCitation[];
  /** When the vote was most recently cast. Overwritten on every recast. */
  lastCast?: string | undefined;
}

export enum Vote_Position {
  Unspecified = "Unspecified",
  For = "For",
  Against = "Against",
  Abstain = "Abstain",
}

/** PropCitation is a half-open character range in a prop's `description`. */
export interface PropCitation {
  start: number;
  end: number;
}

export interface PropListRequest {
  topicId: string;
}

export interface PropList {
  items: Prop[];
}

export interface PropGetRequest {
  topicId: string;
  propId: string;
}

/** PropCreateRequest takes no author: it is the authenticated user. */
export interface PropCreateRequest {
  topicId: string;
  type: Prop_Type;
  description: string;
}

export interface VoteListRequest {
  topicId: string;
  propId: string;
}

/** VoteList is the only way to read a prop's votes. */
export interface VoteList {
  items: Vote[];
}

/**
 * VoteSetRequest sets rather than creates: it replaces the caller's previous
 * vote on this prop.
 */
export interface VoteSetRequest {
  topicId: string;
  propId: string;
  position: Vote_Position;
  explanation: string;
  citations: PropCitation[];
}
