// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/protocol.proto

/* eslint-disable */
import type { ListMetadata } from "./common.js";

export const protobufPackage = "metacensus.v1";

/** Protocols: the extraction form a topic's reviewers fill in per paper. */

/** Protocol is an ordered set of sections, each an ordered set of elements. */
export interface Protocol {
  id: string;
  title: string;
  protocolSections: ProtocolSection[];
}

/** ProtocolSection is a titled group of elements, ordered by `sort_order`. */
export interface ProtocolSection {
  id: string;
  title: string;
  sortOrder: number;
  protocolElements: ProtocolElement[];
}

/** ProtocolElement is one field of the extraction form. */
export interface ProtocolElement {
  id: string;
  name: string;
  /**
   * An HTML input type, used verbatim as `<input type=…>`: `text`, `number`,
   * `date`, `textarea`, `radio` or `checkbox`.
   */
  type: string;
  label: string;
  placeholder: string;
  required: boolean;
  /** Only meaningful for `radio` and `checkbox`. */
  options: ProtocolElementOption[];
  sortOrder: number;
}

/** ProtocolElementOption is one choice of a radio or checkbox element. */
export interface ProtocolElementOption {
  name: string;
  value: string;
}

/** ProtocolTemplate is a reusable protocol a topic can start from. */
export interface ProtocolTemplate {
  id: string;
  title: string;
  protocolSections: ProtocolSection[];
}

/**
 * ProtocolCreateRequest is the body of `POST /protocol/create`, which returns
 * the created `Protocol`.
 */
export interface ProtocolCreateRequest {
  protocol?: ProtocolCreateRequest_Draft | undefined;
}

/**
 * Draft is a protocol that does not exist yet. Ids on its sections and
 * elements are client-side scratch values and are ignored.
 */
export interface ProtocolCreateRequest_Draft {
  title: string;
  topicId: string;
  sections: ProtocolSection[];
}

/**
 * ProtocolEditRequest is the body of `POST /protocol/edit`, which returns the
 * updated `Protocol`. A section or element with a positive id is updated in
 * place; any other id inserts a new one. Omitting one does not delete it.
 */
export interface ProtocolEditRequest {
  protocolId: string;
  sections: ProtocolSection[];
}

/**
 * ProtocolTemplateListRequest is the body of `POST /protocol-template`. No
 * parameters.
 */
export interface ProtocolTemplateListRequest {
}

/** ProtocolTemplateList is the response to `POST /protocol-template`. */
export interface ProtocolTemplateList {
  items: ProtocolTemplate[];
  metadata?: ListMetadata | undefined;
}

/**
 * ProtocolElementListRequest is the body of `POST /protocol-element`, which
 * lists the premade elements the protocol editor offers. No parameters.
 */
export interface ProtocolElementListRequest {
}

/**
 * ProtocolElementList is the response to `POST /protocol-element`. These
 * elements belong to no section, so their `sort_order` is unset.
 */
export interface ProtocolElementList {
  items: ProtocolElement[];
  metadata?: ListMetadata | undefined;
}
