// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/topic.proto

/* eslint-disable */

export const protobufPackage = "metacensus.v1";

/** Topics and their membership. */

/** Topic is a systematic review in progress. */
export interface Topic {
  id: string;
  created?: string | undefined;
  name: string;
  description: string;
}

export interface ListTopicsRequest {
}

export interface TopicList {
  items: Topic[];
}

export interface GetTopicRequest {
  topicId: string;
}

export interface CreateTopicRequest {
  name: string;
  description: string;
}

export interface GetProtocolRequest {
  topicId: string;
}

/**
 * Member is a user's membership of a topic. No backend implements the member
 * routes yet.
 */
export interface Member {
  /** The member's user id, not an id of the membership itself. */
  id: string;
  /** When the user joined the topic. */
  joined?: string | undefined;
}

export interface ListMembersRequest {
  topicId: string;
}

export interface MemberList {
  items: Member[];
}

export interface GetMemberRequest {
  topicId: string;
  userId: string;
}
