// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/user.proto

/* eslint-disable */

export const protobufPackage = "metacensus.v1";

/** Users. Sign-up and login live in auth.proto. */

export interface User {
  id: string;
  name: string;
  email: string;
  country: string;
  created?: string | undefined;
}

export interface ListUsersRequest {
}

export interface UserList {
  items: User[];
}

export interface GetUserRequest {
  userId: string;
}

/** GetSelfRequest is empty: the user is the authenticated one. */
export interface GetSelfRequest {
}
