// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/user.proto

/* eslint-disable */
import type { UserContent, UserSignature } from "./common.js";

export const protobufPackage = "metacensus.v1";

/** Users. Sign-up and login live in auth.proto. */

/**
 * User is a signed record, and the key directory: reading a user yields the
 * `public_key` its enrolling signature carried, which is how a verifier resolves
 * a `key_id`.
 */
export interface User {
  /** Minted by the server, outside the signature: the record's address. */
  id: string;
  /**
   * When the server recorded the write. The server's observation; the claimed
   * time is in UserSignature.signing_time.
   */
  recorded?: string | undefined;
  content?: UserContent | undefined;
  userSignature?: UserSignature | undefined;
}

export interface UserListRequest {
}

export interface UserList {
  items: User[];
}

export interface UserGetRequest {
  userId: string;
}

/** SelfGetRequest is empty: the user is the authenticated one. */
export interface SelfGetRequest {
}
