// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               unknown
// source: metacensus/v1/user.proto

/* eslint-disable */
import type { UserContent, UserSignature } from "./common.js";

export const protobufPackage = "metacensus.v1";

/** Users. Sign-up and login live in auth.proto. */

/**
 * User is a signed record: the server's own fields, the content its owner
 * signed, and the signature over that content.
 *
 * **This surface is also the key directory.** `user_signature.public_key` on a
 * user's enrolling signature is how anyone verifies that user's other
 * signatures, so reading a user is how a verifier resolves a `key_id`.
 */
export interface User {
  /**
   * Minted by the server, and therefore outside the signature: a client cannot
   * be trusted to choose its own key, so it cannot have signed one. This id is
   * the record's *address*; nothing it addresses changes meaning when it
   * changes.
   */
  id: string;
  /**
   * When the server recorded the write. The server's observation, outside the
   * signature; `content`'s signature carries the claimed time. See
   * UserSignature.signing_time for what the pair does and does not bound.
   */
  recorded?: string | undefined;
  content?: UserContent | undefined;
  userSignature?: UserSignature | undefined;
}

export interface UserListRequest {
}

export interface UserList {
  items: User[];
}

export interface UserGetRequest {
  userId: string;
}

/** SelfGetRequest is empty: the user is the authenticated one. */
export interface SelfGetRequest {
}
