// Code generated by cmd/routegen. DO NOT EDIT.

// Package routes is the route table of /metacensus/api/v1, generated from the
// google.api.http annotations in metacensus/v1/routes.proto.
package routes

// Route is one declared route. Path is relative to /metacensus/api/v1 and
// spells its parameters {lowerCamelCase}, as the wire does. Body is "*" when
// the whole request message travels in the body and empty when none does.
type Route struct {
	RPC      string
	Method   string
	Path     string
	Params   []string
	Body     string
	Request  string
	Response string
}

// Routes is every route, in declaration order.
var Routes = []Route{
	{RPC: "Healthcheck", Method: "GET", Path: "/healthcheck", Params: nil, Body: "", Request: "HealthcheckRequest", Response: "HealthcheckResponse"},
	{RPC: "Login", Method: "POST", Path: "/login", Params: nil, Body: "*", Request: "LoginRequest", Response: "Session"},
	{RPC: "SignUp", Method: "POST", Path: "/signup", Params: nil, Body: "*", Request: "SignUpRequest", Response: "Session"},
	{RPC: "Logout", Method: "POST", Path: "/logout", Params: nil, Body: "", Request: "LogoutRequest", Response: "LogoutResponse"},
	{RPC: "ListUsers", Method: "GET", Path: "/user", Params: nil, Body: "", Request: "UserListRequest", Response: "UserList"},
	{RPC: "GetUser", Method: "GET", Path: "/user/{userId}", Params: []string{"userId"}, Body: "", Request: "UserGetRequest", Response: "User"},
	{RPC: "GetSelf", Method: "GET", Path: "/self", Params: nil, Body: "", Request: "SelfGetRequest", Response: "User"},
	{RPC: "ListTopics", Method: "GET", Path: "/topic", Params: nil, Body: "", Request: "TopicListRequest", Response: "TopicList"},
	{RPC: "GetTopic", Method: "GET", Path: "/topic/{topicId}", Params: []string{"topicId"}, Body: "", Request: "TopicGetRequest", Response: "Topic"},
	{RPC: "CreateTopic", Method: "POST", Path: "/topic", Params: nil, Body: "*", Request: "TopicCreateRequest", Response: "Topic"},
	{RPC: "GetTopicProtocol", Method: "GET", Path: "/topic/{topicId}/protocol", Params: []string{"topicId"}, Body: "", Request: "TopicProtocolRequest", Response: "Protocol"},
	{RPC: "ListMembers", Method: "GET", Path: "/topic/{topicId}/member", Params: []string{"topicId"}, Body: "", Request: "MemberListRequest", Response: "MemberList"},
	{RPC: "GetMember", Method: "GET", Path: "/topic/{topicId}/member/{userId}", Params: []string{"topicId", "userId"}, Body: "", Request: "MemberGetRequest", Response: "Member"},
	{RPC: "ListProps", Method: "GET", Path: "/topic/{topicId}/prop", Params: []string{"topicId"}, Body: "", Request: "PropListRequest", Response: "PropList"},
	{RPC: "GetProp", Method: "GET", Path: "/topic/{topicId}/prop/{propId}", Params: []string{"topicId", "propId"}, Body: "", Request: "PropGetRequest", Response: "Prop"},
	{RPC: "CreateProp", Method: "POST", Path: "/topic/{topicId}/prop", Params: []string{"topicId"}, Body: "*", Request: "PropCreateRequest", Response: "Prop"},
	{RPC: "ListVotes", Method: "GET", Path: "/topic/{topicId}/prop/{propId}/vote", Params: []string{"topicId", "propId"}, Body: "", Request: "VoteListRequest", Response: "VoteList"},
	{RPC: "SetVote", Method: "POST", Path: "/topic/{topicId}/prop/{propId}/vote", Params: []string{"topicId", "propId"}, Body: "*", Request: "VoteSetRequest", Response: "Vote"},
	{RPC: "ListPapers", Method: "POST", Path: "/paper", Params: nil, Body: "*", Request: "PaperListRequest", Response: "PaperList"},
	{RPC: "CreatePaper", Method: "POST", Path: "/paper/create", Params: nil, Body: "*", Request: "PaperCreateRequest", Response: "Paper"},
	{RPC: "LookupPaper", Method: "GET", Path: "/paper/lookup", Params: nil, Body: "", Request: "PaperLookupRequest", Response: "PaperLookupResponse"},
	{RPC: "CreateProtocol", Method: "POST", Path: "/protocol", Params: nil, Body: "*", Request: "ProtocolCreateRequest", Response: "Protocol"},
	{RPC: "EditProtocol", Method: "POST", Path: "/protocol/{protocolId}", Params: []string{"protocolId"}, Body: "*", Request: "ProtocolEditRequest", Response: "Protocol"},
	{RPC: "ListProtocolTemplates", Method: "POST", Path: "/protocol-template", Params: nil, Body: "", Request: "ProtocolTemplateListRequest", Response: "ProtocolTemplateList"},
	{RPC: "ListProtocolElements", Method: "POST", Path: "/protocol-element", Params: nil, Body: "", Request: "ProtocolElementListRequest", Response: "ProtocolElementList"},
	{RPC: "GetExtraction", Method: "GET", Path: "/extraction", Params: nil, Body: "", Request: "DataExtractionGetRequest", Response: "DataExtraction"},
	{RPC: "UpsertExtraction", Method: "POST", Path: "/extraction", Params: nil, Body: "*", Request: "DataExtraction", Response: "DataExtraction"},
}
