// Shared types for the public surface, and where the surface-wide answers
// live.
//
// Neither surface types its failures; the HTTP status is the signal. Below
// are the statuses this surface answers with, on every route and on paths
// no route claims (404, 405) — prose because `google.api.http` cannot
// express responses. See README.md, "The two surfaces" and "Errors on the
// two surfaces", for why.
//
//   400  the submission was not valid, or the body was not JSON
//   403  the `Origin` was absent or not allowlisted
//   413  the body exceeded 16 KiB
//   429  the per-client rate limit was exceeded; `Retry-After` carries seconds
//   502  the submission could not be relayed upstream
//   500  something else went wrong
//
// No messages yet: this file is the cross-file typing rule's one exemption,
// so it's where a type shared across this surface's resources would go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metacensus/public/v1/common.proto

package metacensuspublicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_metacensus_public_v1_common_proto protoreflect.FileDescriptor

const file_metacensus_public_v1_common_proto_rawDesc = "" +
	"\n" +
	"!metacensus/public/v1/common.proto\x12\x14metacensus.public.v1BFZDgithub.com/metacensus/api/go/metacensus/public/v1;metacensuspublicv1b\x06proto3"

var file_metacensus_public_v1_common_proto_goTypes = []any{}
var file_metacensus_public_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metacensus_public_v1_common_proto_init() }
func file_metacensus_public_v1_common_proto_init() {
	if File_metacensus_public_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacensus_public_v1_common_proto_rawDesc), len(file_metacensus_public_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacensus_public_v1_common_proto_goTypes,
		DependencyIndexes: file_metacensus_public_v1_common_proto_depIdxs,
	}.Build()
	File_metacensus_public_v1_common_proto = out.File
	file_metacensus_public_v1_common_proto_goTypes = nil
	file_metacensus_public_v1_common_proto_depIdxs = nil
}
